In [1]:
!pip install pandas numpy matplotlib pyarrow scikit-learn tkan "jax[cuda12]" keras_sig tkan sig_rnn --upgrade

Collecting pandas
  Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 20.9 MB/s eta 0:00:0000:0100:01
Collecting numpy
  Downloading numpy-2.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 32.4 MB/s eta 0:00:0000:0100:01
Collecting matplotlib
  Downloading matplotlib-3.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 36.8 MB/s eta 0:00:00a 0:00:01
Collecting pyarrow
  Downloading pyarrow-18.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (40.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.1/40.1 MB 31.3 MB/s eta 0:00:0000:0100:01
Collecting scikit-learn
  Downloading scikit_learn-1.6.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.5/13.5 MB 38.9 MB/s eta 0:00:0000:0100:01
Collecting tkan
  Downloading tkan-0.4.3-py3-none-any.whl (7.4 kB)
Collecting jax[cuda12]
  Downloading jax-0.4.38-py3-none-any.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 41.9 MB/s eta 0:00:00a 0:00:01
Collecting keras_sig
  Downloading keras_sig-1.0.2-py3-none-any.whl (12 kB)
Collecting sig_rnn
  Downloading sig_rnn-0.1.0-py3-none-any.whl (8.4 kB)
Collecting tzdata>=2022.7
  Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 KB 36.8 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.0/508.0 KB 39.8 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (24.2)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (324 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 325.0/325.0 KB 28.3 MB/s eta 0:00:00
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.55.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 43.5 MB/s eta 0:00:0000:0100:01
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.4.8-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 42.5 MB/s eta 0:00:0000:01
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib) (2.4.7)
Collecting pillow>=8
  Downloading pillow-11.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 45.1 MB/s eta 0:00:00a 0:00:01
Collecting scipy>=1.6.0
  Downloading scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 MB 30.6 MB/s eta 0:00:0000:0100:01
Collecting joblib>=1.2.0
  Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 KB 38.7 MB/s eta 0:00:00
Collecting threadpoolctl>=3.1.0
  Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Collecting keras_efficient_kan<0.2.0,>=0.1.9
  Downloading keras_efficient_kan-0.1.10-py3-none-any.whl (3.5 kB)
Collecting keras<4.0.0,>=3.0.0
  Downloading keras-3.7.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 53.0 MB/s eta 0:00:00
Collecting opt_einsum
  Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 KB 11.1 MB/s eta 0:00:00
Collecting ml_dtypes>=0.4.0
  Downloading ml_dtypes-0.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 46.7 MB/s eta 0:00:00a 0:00:01
Collecting jaxlib<=0.4.38,>=0.4.38
  Downloading jaxlib-0.4.38-cp310-cp310-manylinux2014_x86_64.whl (101.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 MB 24.9 MB/s eta 0:00:0000:0100:01
Collecting jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38
  Downloading jax_cuda12_plugin-0.4.38-cp310-cp310-manylinux2014_x86_64.whl (16.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.2/16.2 MB 44.2 MB/s eta 0:00:0000:0100:01
Collecting jaxtyping<0.3.0,>=0.2.36
  Downloading jaxtyping-0.2.36-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 KB 8.1 MB/s eta 0:00:00
Collecting jax-cuda12-pjrt==0.4.38
  Downloading jax_cuda12_pjrt-0.4.38-py3-none-manylinux2014_x86_64.whl (102.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.7/102.7 MB 23.9 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cudnn-cu12<10.0,>=9.1
  Downloading nvidia_cudnn_cu12-9.6.0.74-py3-none-manylinux_2_27_x86_64.whl (508.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.1/508.1 MB 8.8 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusolver-cu12>=11.4.5.107
  Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (158.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 MB 21.8 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusparse-cu12>=12.1.0.106
  Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (216.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 MB 18.4 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cuda-nvcc-cu12>=12.6.85
  Downloading nvidia_cuda_nvcc_cu12-12.6.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (21.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.2/21.2 MB 72.8 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cublas-cu12>=12.1.3.1
  Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (393.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 11.2 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cuda-runtime-cu12>=12.1.105
  Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (897 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 KB 67.2 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12>=12.1.105
  Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 83.7 MB/s eta 0:00:0000:0100:01m
Collecting nvidia-cufft-cu12>=11.0.2.54
  Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (200.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 19.3 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nccl-cu12>=2.18.1
  Downloading nvidia_nccl_cu12-2.23.4-py3-none-manylinux2014_x86_64.whl (199.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.0/199.0 MB 18.2 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nvjitlink-cu12>=12.1.105
  Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (19.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 35.1 MB/s eta 0:00:0000:0100:01
Collecting h5py
  Downloading h5py-3.12.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 58.8 MB/s eta 0:00:00a 0:00:01
Collecting rich
  Downloading rich-13.9.4-py3-none-any.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.4/242.4 KB 30.5 MB/s eta 0:00:00
Collecting absl-py
  Downloading absl_py-2.1.0-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 KB 20.9 MB/s eta 0:00:00
Collecting namex
  Downloading namex-0.0.8-py3-none-any.whl (5.8 kB)
Collecting optree
  Downloading optree-0.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (381 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.3/381.3 KB 36.0 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.10/dist-packages (from optree->keras<4.0.0,>=3.0.0->tkan) (4.12.2)
Collecting markdown-it-py>=2.2.0
  Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 KB 12.6 MB/s eta 0:00:00
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras<4.0.0,>=3.0.0->tkan) (2.18.0)
Collecting mdurl~=0.1
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pytz, namex, jax-cuda12-pjrt, tzdata, threadpoolctl, pyarrow, pillow, optree, opt_einsum, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvcc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, mdurl, kiwisolver, joblib, jaxtyping, jax-cuda12-plugin, fonttools, cycler, absl-py, scipy, pandas, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, ml_dtypes, markdown-it-py, h5py, contourpy, scikit-learn, rich, nvidia-cusolver-cu12, matplotlib, jaxlib, keras, jax, keras_sig, keras_efficient_kan, tkan, sig_rnn
Successfully installed absl-py-2.1.0 contourpy-1.3.1 cycler-0.12.1 fonttools-4.55.3 h5py-3.12.1 jax-0.4.38 jax-cuda12-pjrt-0.4.38 jax-cuda12-plugin-0.4.38 jaxlib-0.4.38 jaxtyping-0.2.36 joblib-1.4.2 keras-3.7.0 keras_efficient_kan-0.1.10 keras_sig-1.0.2 kiwisolver-1.4.8 markdown-it-py-3.0.0 matplotlib-3.10.0 mdurl-0.1.2 ml_dtypes-0.5.0 namex-0.0.8 numpy-2.2.1 nvidia-cublas-cu12-12.6.4.1 nvidia-cuda-cupti-cu12-12.6.80 nvidia-cuda-nvcc-cu12-12.6.85 nvidia-cuda-runtime-cu12-12.6.77 nvidia-cudnn-cu12-9.6.0.74 nvidia-cufft-cu12-11.3.0.4 nvidia-cusolver-cu12-11.7.1.2 nvidia-cusparse-cu12-12.5.4.2 nvidia-nccl-cu12-2.23.4 nvidia-nvjitlink-cu12-12.6.85 opt_einsum-3.4.0 optree-0.13.1 pandas-2.2.3 pillow-11.1.0 pyarrow-18.1.0 pytz-2024.2 rich-13.9.4 scikit-learn-1.6.0 scipy-1.14.1 sig_rnn-0.1.0 threadpoolctl-3.5.0 tkan-0.4.3 tzdata-2024.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

# Exploring Signature-Based Gating in LSTM and GRU Networks

This notebook investigates the integration of path signatures into classical recurrent neural network architectures, focusing on their application in gating mechanisms. We explore two different approaches:

1. **Signature-Based LSTM**: A modified LSTM where the forget gate is controlled by path signatures instead of traditional linear transformations, while maintaining the standard computation for input and output gates.

2. **Signature-Based GRU**: An adaptation of the Gated Recurrent Unit where the reset gate computation is enhanced with path signatures, preserving the original update gate mechanics.

## Motivation

Traditional LSTM and GRU architectures use linear transformations followed by nonlinear activations for their gating mechanisms. However, path signatures provide a rich, hierarchical representation of sequential data that could potentially offer more sophisticated control over information flow in these networks. By incorporating signatures into specific gating mechanisms, we aim to:

- Capture higher-order temporal patterns in the input sequences
- Provide better control over long-term dependencies through signature-based forget/reset mechanisms
- Maintain the proven effectiveness of standard gates while enhancing critical gates with signature computations

## Implementation Details

The notebook implements these architectures using Keras 3's backend-agnostic framework, ensuring compatibility across TensorFlow, JAX, and PyTorch backends. Each implementation:
- Uses streaming signatures to maintain temporal coherence
- Normalizes signature values by sequence length
- Maintains the original architecture's core functionality while enhancing specific gates
- Computes signatures at the RNN level to optimize computational efficiency

## Usage

The implementations can be used as drop-in replacements for standard LSTM and GRU layers in any Keras model. They accept the same input formats and provide the same output structures as their traditional counterparts.

---

*Note: This research explores the potential benefits of combining classical RNN architectures with modern signature methods for enhanced temporal data processing.*

In [2]:
import os
BACKEND = 'jax' # You can use any backend here 
os.environ['KERAS_BACKEND'] = BACKEND

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import keras
from keras.models import Sequential
from keras.layers import LSTM, Dense, Input, Flatten, GRU

from sklearn.metrics import r2_score
from sklearn.metrics import root_mean_squared_error

from tkan import TKAN
from keras_sig import SigLayer

from sig_rnn import SignatureGRU,SignatureLSTM

import time

keras.utils.set_random_seed(1) 

N_MAX_EPOCHS = 1000
BATCH_SIZE = 128
early_stopping_callback = lambda : keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.00001,
    patience=10,
    mode="min",
    restore_best_weights=True,
    start_from_epoch=6,
)
lr_callback = lambda : keras.callbacks.ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.25,
    patience=5,
    mode="min",
    min_delta=0.00001,
    min_lr=0.000025,
    verbose=0,
)
callbacks = lambda : [early_stopping_callback(), lr_callback(), keras.callbacks.TerminateOnNaN()]

# Data

In [3]:
df = pd.read_parquet('data.parquet')
df = df[(df.index >= pd.Timestamp('2020-01-01')) & (df.index < pd.Timestamp('2023-01-01'))]
assets = ['BTC', 'ETH', 'ADA', 'XMR', 'EOS', 'MATIC', 'TRX', 'FTM', 'BNB', 'XLM', 'ENJ', 'CHZ', 'BUSD', 'ATOM', 'LINK', 'ETC', 'XRP', 'BCH', 'LTC']
df = df[[c for c in df.columns if 'quote asset volume' in c and any(asset in c for asset in assets)]]
df.columns = [c.replace(' quote asset volume', '') for c in df.columns]
display(df)

,BTC,ADA,XMR,EOS,CHZ,MATIC,TRX,ENJ,FTM,BNB,XLM,BUSD,ATOM,LTC,LINK,ETC,ETH,XRP,BCH
group,,,,,,,,,,,,,,,,,,,
2020-01-01 00:00:00,3.675857e+06,38189.176211,4.539598e+04,94778.577031,817.146319,31003.791035,481993.354990,15241.945783,1165.788613,8.498617e+05,9460.819556,1.352376e+04,31986.972694,1.165827e+05,24281.170262,56488.402352,1.000930e+06,2.579254e+05,178258.749391
2020-01-01 01:00:00,6.365953e+06,51357.010954,3.348395e+04,593292.135445,886.460339,84465.335718,533668.554562,11896.843688,413.844612,7.405759e+05,37141.909518,2.531605e+04,81777.666046,2.830715e+05,51190.975142,182102.074213,1.474278e+06,4.520609e+05,615321.025242
2020-01-01 02:00:00,4.736719e+06,36164.263914,1.573255e+04,266732.556000,1819.795050,113379.718506,387049.986770,30109.770521,3559.965968,1.039091e+06,16878.822627,1.390886e+04,195731.175551,2.402871e+05,28721.756184,134063.422732,9.940256e+05,4.414948e+05,221535.645771
2020-01-01 03:00:00,5.667367e+06,24449.953815,2.575105e+04,124516.579473,2979.655803,41771.707995,450772.139235,6732.833578,4076.415482,4.975018e+05,9049.223394,2.251969e+04,120113.343316,1.613043e+05,29596.222534,131094.172168,6.473610e+05,1.886061e+05,397185.950571
2020-01-01 04:00:00,3.379094e+06,44502.669843,6.295563e+04,421819.671410,1023.388675,22254.756114,284788.973752,846.938455,633.367505,4.751285e+05,7254.260203,1.122460e+04,19989.169106,2.214516e+05,54514.370016,134937.122201,4.430067e+05,2.279373e+05,316499.137509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-31 19:00:00,6.704605e+07,581680.400510,3.873989e+05,48359.865300,199491.822800,890911.573610,225136.420055,40281.859330,159553.944500,9.889098e+05,39230.588600,6.560756e+06,180809.784710,9.964355e+05,190664.976300,181340.756100,7.738029e+06,1.413563e+06,35409.149500
2022-12-31 20:00:00,4.344849e+07,323561.762270,1.379392e+05,37858.704700,173057.240300,333511.762200,157069.026827,42228.830930,270251.374500,6.032059e+05,52964.531800,7.255324e+06,276013.421720,1.173164e+06,265727.950340,90513.087600,4.278879e+06,1.113527e+06,42674.516600
2022-12-31 21:00:00,5.992803e+07,455185.698060,2.445869e+05,79538.050600,107544.609700,525037.759990,180404.744820,27446.620810,198885.610000,1.386864e+06,44485.594800,8.712142e+06,476151.071190,6.820723e+05,265687.852060,85399.066100,4.643401e+06,1.373231e+06,38027.858800
2022-12-31 22:00:00,1.106669e+08,763590.393960,1.486058e+06,119816.048000,227360.873900,940456.693720,378767.904610,37877.840280,179819.382700,1.387985e+06,43947.636100,5.517835e+06,558172.963150,8.838422e+05,678706.662170,319377.553800,1.143952e+07,3.006036e+06,50730.511300
2022-12-31 23:00:00,8.217183e+07,916995.764890,1.292763e+05,101125.121600,181794.887300,615235.478960,201939.176223,27857.744420,305403.731200,1.069728e+06,80571.059200,6.251872e+06,320158.642350,9.486568e+05,546064.757390,135623.176400,7.086714e+06,8.907798e+06,85765.409200

In [4]:
class MinMaxScaler:
    def __init__(self, feature_axis=None, minmax_range=(0, 1)):
        """
        Initialize the MinMaxScaler.
        Args:
        feature_axis (int, optional): The axis that represents the feature dimension if applicable.
                                      Use only for 3D data to specify which axis is the feature axis.
                                      Default is None, automatically managed based on data dimensions.
        """
        self.feature_axis = feature_axis
        self.min_ = None
        self.max_ = None
        self.scale_ = None
        self.minmax_range = minmax_range # Default range for scaling (min, max)

    def fit(self, X):
        """
        Fit the scaler to the data based on its dimensionality.
        Args:
        X (np.array): The data to fit the scaler on.
        """
        if X.ndim == 3 and self.feature_axis is not None:  # 3D data
            axis = tuple(i for i in range(X.ndim) if i != self.feature_axis)
            self.min_ = np.min(X, axis=axis)
            self.max_ = np.max(X, axis=axis)
        elif X.ndim == 2:  # 2D data
            self.min_ = np.min(X, axis=0)
            self.max_ = np.max(X, axis=0)
        elif X.ndim == 1:  # 1D data
            self.min_ = np.min(X)
            self.max_ = np.max(X)
        else:
            raise ValueError("Data must be 1D, 2D, or 3D.")

        self.scale_ = self.max_ - self.min_
        return self

    def transform(self, X):
        """
        Transform the data using the fitted scaler.
        Args:
        X (np.array): The data to transform.
        Returns:
        np.array: The scaled data.
        """
        X_scaled = (X - self.min_) / self.scale_
        X_scaled = X_scaled * (self.minmax_range[1] - self.minmax_range[0]) + self.minmax_range[0]
        return X_scaled

    def fit_transform(self, X):
        """
        Fit to data, then transform it.
        Args:
        X (np.array): The data to fit and transform.
        Returns:
        np.array: The scaled data.
        """
        return self.fit(X).transform(X)

    def inverse_transform(self, X_scaled):
        """
        Inverse transform the scaled data to original data.
        Args:
        X_scaled (np.array): The scaled data to inverse transform.
        Returns:
        np.array: The original data scale.
        """
        X = (X_scaled - self.minmax_range[0]) / (self.minmax_range[1] - self.minmax_range[0])
        X = X * self.scale_ + self.min_
        return X

def generate_data(df, sequence_length, n_ahead = 1):
    #Case without known inputs
    scaler_df = df.copy().shift(n_ahead).rolling(24 * 14).median()
    tmp_df = df.copy() / scaler_df
    tmp_df = tmp_df.iloc[24 * 14 + n_ahead:].fillna(0.)
    scaler_df = scaler_df.iloc[24 * 14 + n_ahead:].fillna(0.)
    def prepare_sequences(df, scaler_df, n_history, n_future):
        X, y, y_scaler = [], [], []
        num_features = df.shape[1]
        
        # Iterate through the DataFrame to create sequences
        for i in range(n_history, len(df) - n_future + 1):
            # Extract the sequence of past observations
            X.append(df.iloc[i - n_history:i].values)
            # Extract the future values of the first column
            y.append(df.iloc[i:i + n_future,0:1].values)
            y_scaler.append(scaler_df.iloc[i:i + n_future,0:1].values)
        
        X, y, y_scaler = np.array(X), np.array(y), np.array(y_scaler)
        return X, y, y_scaler
    
    # Prepare sequences
    X, y, y_scaler = prepare_sequences(tmp_df, scaler_df, sequence_length, n_ahead)
    
    # Split the dataset into training and testing sets
    train_test_separation = int(len(X) * 0.8)
    X_train_unscaled, X_test_unscaled = X[:train_test_separation], X[train_test_separation:]
    y_train_unscaled, y_test_unscaled = y[:train_test_separation], y[train_test_separation:]
    y_scaler_train, y_scaler_test = y_scaler[:train_test_separation], y_scaler[train_test_separation:]
    
    # Generate the data
    X_scaler = MinMaxScaler(feature_axis=2)
    X_train = X_scaler.fit_transform(X_train_unscaled)
    X_test = X_scaler.transform(X_test_unscaled)
    
    y_scaler = MinMaxScaler(feature_axis=2)
    y_train = y_scaler.fit_transform(y_train_unscaled)
    y_test = y_scaler.transform(y_test_unscaled)
    
    y_train = y_train.reshape(y_train.shape[0], -1) 
    y_test = y_test.reshape(y_test.shape[0], -1)
    return X_scaler, X_train, X_test, X_train_unscaled, X_test_unscaled, y_scaler, y_train, y_test, y_train_unscaled, y_test_unscaled, y_scaler_train, y_scaler_test

In [5]:
n_aheads = [1, 9, 15]
models = [
    "SignatureLSTM-2-2",
    "SignatureGRU-2-2",
    "SignatureLSTM-3-2",
    "SignatureGRU-3-2",
    "SignatureLSTM-3-3",
    "SignatureGRU-3-3",
    "SignatureLSTM-2_10-2",
    "SignatureGRU-2_10-2",
    "SignatureLSTM-3-3-3",
    "SignatureGRU-3-3-3",
    "SignatureLSTM-4-4",
    "SignatureGRU-4-4",
    "SignatureLSTM-3-3-flatten",
    "SignatureGRU-3-3-flatten",
    "GRU",
    "LSTM",
    "GRU-3",
    "LSTM-3",
    "GRU-flatten",
    "LSTM-flatten",
 ]

results = {model: {n_ahead: [] for n_ahead in n_aheads} for model in models}
results_rmse = {model: {n_ahead: [] for n_ahead in n_aheads} for model in models}
time_results = {model: {n_ahead: [] for n_ahead in n_aheads} for model in models}
for n_ahead in n_aheads:
    sequence_length = max(45, 5 * n_ahead)
    for run in range(5):
        X_scaler, X_train, X_test, X_train_unscaled, X_test_unscaled, y_scaler, y_train, y_test, y_train_unscaled, y_test_unscaled, y_scaler_train, y_scaler_test = generate_data(df, sequence_length, n_ahead)
        
        for model_id in models:

            if model_id == 'LSTM':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    LSTM(100, return_sequences=True),
                    LSTM(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'GRU':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    GRU(100, return_sequences=True),
                    GRU(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-2-2':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, return_sequences=True),
                    SignatureLSTM(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-2-2':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, return_sequences=True),
                    SignatureGRU(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-3-2':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, signature_depth=3, return_sequences=True),
                    SignatureLSTM(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-3-2':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, signature_depth=3, return_sequences=True),
                    SignatureGRU(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-3-3':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, signature_depth=3, return_sequences=True),
                    SignatureLSTM(100, signature_depth=3, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-3-3':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, signature_depth=3, return_sequences=True),
                    SignatureGRU(100, signature_depth=3, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-2_10-2':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, signature_input_size=10, return_sequences=True),
                    SignatureLSTM(100, signature_input_size=10, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-2_10-2':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, signature_input_size=10, return_sequences=True),
                    SignatureGRU(100, signature_input_size=10, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'LSTM-flatten':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    LSTM(100, return_sequences=True),
                    LSTM(100, return_sequences=True),
                    Flatten(),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'GRU-flatten':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    GRU(100, return_sequences=True),
                    GRU(100, return_sequences=True),
                    Flatten(),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'LSTM-3':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    LSTM(100, return_sequences=True),
                    LSTM(100, return_sequences=True),
                    LSTM(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'GRU-3':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    GRU(100, return_sequences=True),
                    GRU(100, return_sequences=True),
                    GRU(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-3-3-3':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, signature_depth=3, return_sequences=True),
                    SignatureLSTM(100, signature_depth=3, return_sequences=True),
                    SignatureLSTM(100, signature_depth=3, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-3-3-3':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, signature_depth=3, return_sequences=True),
                    SignatureGRU(100, signature_depth=3, return_sequences=True),
                    SignatureGRU(100, signature_depth=3, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-4-4':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, signature_depth=4, return_sequences=True),
                    SignatureLSTM(100, signature_depth=4, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-4-4':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, signature_depth=4, return_sequences=True),
                    SignatureGRU(100, signature_depth=4, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-3-3-flatten':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, signature_depth=3, return_sequences=True),
                    SignatureLSTM(100, signature_depth=3, return_sequences=True),
                    Flatten(),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-3-3-flatten':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, signature_depth=3, return_sequences=True),
                    SignatureGRU(100, signature_depth=3, return_sequences=True),
                    Flatten(),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            else:
                raise ValueError

            optimizer = keras.optimizers.Adam(0.001)
            model.compile(optimizer=optimizer, loss='mean_squared_error', jit_compile=True)
            if run==0:
                model.summary()
                
            # Fit the model
            start_time = time.time()
            history = model.fit(X_train, y_train, batch_size=BATCH_SIZE, epochs=N_MAX_EPOCHS, validation_split=0.2, callbacks=callbacks(), shuffle=True, verbose = False)
            end_time = time.time()
            time_results[model_id][n_ahead].append(end_time - start_time)
            # Evaluate the model on the test set
            preds = model.predict(X_test, verbose=False)
            r2 = r2_score(y_true=y_test, y_pred=preds)
            print(model_id, end_time - start_time, r2)
            rmse = root_mean_squared_error(y_true=y_test, y_pred=preds)
            results[model_id][n_ahead].append(r2)
            results_rmse[model_id][n_ahead].append(rmse)
    
            del model
            del optimizer
                

print('R2 scores')
print('Means:')
df_mean_r2 = pd.DataFrame({model_id: {n_ahead: np.mean(results[model_id][n_ahead]) for n_ahead in n_aheads} for model_id in results.keys()})
df_mean_r2.to_csv('volume_mean_r2.csv')
display(df_mean_r2)
df_mean_rmse = pd.DataFrame({model_id: {n_ahead: np.mean(results_rmse[model_id][n_ahead]) for n_ahead in n_aheads} for model_id in results_rmse.keys()})
df_mean_rmse.to_csv('volume_mean_rmse.csv')
display(df_mean_rmse)
print('Std:')
df_std_r2 = pd.DataFrame({model_id: {n_ahead: np.std(results[model_id][n_ahead]) for n_ahead in n_aheads} for model_id in results.keys()})
df_std_r2.to_csv('volume_std_r2.csv')
display(df_std_r2)
df_std_rmse = pd.DataFrame({model_id: {n_ahead: np.std(results_rmse[model_id][n_ahead]) for n_ahead in n_aheads} for model_id in results_rmse.keys()})
df_std_rmse.to_csv('volume_std_rmse.csv')
display(df_std_rmse)
print('Training Times')
df_mean_time = pd.DataFrame({model_id: {n_ahead: np.mean(time_results[model_id][n_ahead]) for n_ahead in n_aheads} for model_id in time_results.keys()})
df_mean_time.to_csv('volume_mean_time.csv')
display(df_mean_time)
df_std_time = pd.DataFrame({model_id: {n_ahead: np.std(time_results[model_id][n_ahead]) for n_ahead in n_aheads} for model_id in time_results.keys()})
df_std_time.to_csv('volume_std_time.csv')
display(df_std_time)

Model: "SignatureLSTM-2-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm (SignatureLSTM)  │ (None, 45, 100)        │        39,195 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_1                │ (None, 100)            │        63,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 103,196 (403.11 KB)

 Trainable params: 103,196 (403.11 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-2-2 83.23044180870056 0.4101068294963901

Model: "SignatureGRU-2-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru (SignatureGRU)    │ (None, 45, 100)        │        27,195 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_1 (SignatureGRU)  │ (None, 100)            │        43,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 71,096 (277.72 KB)

 Trainable params: 71,096 (277.72 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-2-2 42.56610441207886 0.3969611035406365

Model: "SignatureLSTM-3-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_2                │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_3                │ (None, 100)            │        63,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 115,696 (451.94 KB)

 Trainable params: 115,696 (451.94 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-2 90.01735758781433 0.39955218106575974

Model: "SignatureGRU-3-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_2 (SignatureGRU)  │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_3 (SignatureGRU)  │ (None, 100)            │        43,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 83,596 (326.55 KB)

 Trainable params: 83,596 (326.55 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-2 43.2162389755249 0.4033581864131731

Model: "SignatureLSTM-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_4                │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_5                │ (None, 100)            │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 128,196 (500.77 KB)

 Trainable params: 128,196 (500.77 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3 94.53126740455627 0.3976564521647816

Model: "SignatureGRU-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_4 (SignatureGRU)  │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_5 (SignatureGRU)  │ (None, 100)            │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 96,096 (375.38 KB)

 Trainable params: 96,096 (375.38 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3 42.92876100540161 0.4018037827522176

Model: "SignatureLSTM-2_10-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_6                │ (None, 45, 100)        │        47,290 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_7                │ (None, 100)            │        72,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119,791 (467.93 KB)

 Trainable params: 119,791 (467.93 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-2_10-2 97.37126445770264 0.38808469595963047

Model: "SignatureGRU-2_10-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_6 (SignatureGRU)  │ (None, 45, 100)        │        35,290 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_7 (SignatureGRU)  │ (None, 100)            │        52,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 87,691 (342.54 KB)

 Trainable params: 87,691 (342.54 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-2_10-2 47.70652961730957 0.40409621781121774

Model: "SignatureLSTM-3-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_8                │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_9                │ (None, 45, 100)        │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_10               │ (None, 100)            │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 204,596 (799.20 KB)

 Trainable params: 204,596 (799.20 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3-3 126.81912899017334 0.4027944658828144

Model: "SignatureGRU-3-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_8 (SignatureGRU)  │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_9 (SignatureGRU)  │ (None, 45, 100)        │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_10 (SignatureGRU) │ (None, 100)            │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 152,396 (595.30 KB)

 Trainable params: 152,396 (595.30 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3-3 62.61533284187317 0.3910210128217714

Model: "SignatureLSTM-4-4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_11               │ (None, 45, 100)        │       114,195 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_12               │ (None, 100)            │       138,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 253,196 (989.05 KB)

 Trainable params: 253,196 (989.05 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-4-4 102.04043912887573 0.3944379079310174

Model: "SignatureGRU-4-4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_11 (SignatureGRU) │ (None, 45, 100)        │       102,195 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_12 (SignatureGRU) │ (None, 100)            │       118,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 221,096 (863.66 KB)

 Trainable params: 221,096 (863.66 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-4-4 54.38698983192444 0.40793916792255047

Model: "SignatureLSTM-3-3-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_13               │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_14               │ (None, 45, 100)        │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_38 (Dense)                │ (None, 1)              │         4,501 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 132,596 (517.95 KB)

 Trainable params: 132,596 (517.95 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3-flatten 132.06034803390503 0.4042583071852166

Model: "SignatureGRU-3-3-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_13 (SignatureGRU) │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_14 (SignatureGRU) │ (None, 45, 100)        │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_41 (Dense)                │ (None, 1)              │         4,501 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,496 (392.56 KB)

 Trainable params: 100,496 (392.56 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3-flatten 55.23312306404114 0.3935861769356285

Model: "GRU"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru (GRU)                       │ (None, 45, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ (None, 100)            │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_44 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97,001 (378.91 KB)

 Trainable params: 97,001 (378.91 KB)

 Non-trainable params: 0 (0.00 B)

GRU 22.54633855819702 0.39864843541283745

Model: "LSTM"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 45, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 100)            │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_45 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 128,501 (501.96 KB)

 Trainable params: 128,501 (501.96 KB)

 Non-trainable params: 0 (0.00 B)

LSTM 14.120237827301025 0.3859268990621493

Model: "GRU-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_2 (GRU)                     │ (None, 45, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_3 (GRU)                     │ (None, 45, 100)        │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_4 (GRU)                     │ (None, 100)            │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_46 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 157,601 (615.63 KB)

 Trainable params: 157,601 (615.63 KB)

 Non-trainable params: 0 (0.00 B)

GRU-3 33.54845976829529 0.39032128782844255

Model: "LSTM-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_2 (LSTM)                   │ (None, 45, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 45, 100)        │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 100)            │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_47 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 208,901 (816.02 KB)

 Trainable params: 208,901 (816.02 KB)

 Non-trainable params: 0 (0.00 B)

LSTM-3 24.451338291168213 0.3770506853287149

Model: "GRU-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_5 (GRU)                     │ (None, 45, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_6 (GRU)                     │ (None, 45, 100)        │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_48 (Dense)                │ (None, 1)              │         4,501 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 101,401 (396.10 KB)

 Trainable params: 101,401 (396.10 KB)

 Non-trainable params: 0 (0.00 B)

GRU-flatten 20.385514974594116 0.38334844071391916

Model: "LSTM-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_5 (LSTM)                   │ (None, 45, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ (None, 45, 100)        │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_49 (Dense)                │ (None, 1)              │         4,501 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 132,901 (519.14 KB)

 Trainable params: 132,901 (519.14 KB)

 Non-trainable params: 0 (0.00 B)

LSTM-flatten 21.52019429206848 0.38120286792320135
SignatureLSTM-2-2 86.65897512435913 0.369762777183144
SignatureGRU-2-2 45.607489585876465 0.4014234608008631
SignatureLSTM-3-2 84.92457389831543 0.3904016961557505
SignatureGRU-3-2 48.516218423843384 0.40636060002099517
SignatureLSTM-3-3 87.77939414978027 0.41434154030469916
SignatureGRU-3-3 42.44713354110718 0.4065390419639542
SignatureLSTM-2_10-2 88.09939885139465 0.38848145711018145
SignatureGRU-2_10-2 44.282501459121704 0.4101517838701424
SignatureLSTM-3-3-3 117.3808081150055 0.40403070247156225
SignatureGRU-3-3-3 69.18363523483276 0.39538486033536935
SignatureLSTM-4-4 100.64062714576721 0.3909229820127311
SignatureGRU-4-4 51.36034893989563 0.39808724210585156
SignatureLSTM-3-3-flatten 126.5150694847107 0.4038558721275859
SignatureGRU-3-3-flatten 48.468679666519165 0.3942191280911429
GRU 17.490081310272217 0.3969403014594942
LSTM 14.3751540184021 0.3908545909297092
GRU-3 27.999972820281982 0.3728237569005597
LSTM-3 26.134700059890747 0.32847501102087706
GRU-flatten 18.541834592819214 0.38664238776937765
LSTM-flatten 14.886133193969727 0.38696965386411586
SignatureLSTM-2-2 84.12429547309875 0.390880332274141
SignatureGRU-2-2 39.54339599609375 0.3979210776641724
SignatureLSTM-3-2 77.76891875267029 0.40462569119355773
SignatureGRU-3-2 47.052053928375244 0.3971456945350912
SignatureLSTM-3-3 84.51138401031494 0.40815123087777916
SignatureGRU-3-3 43.70686459541321 0.404014797181239
SignatureLSTM-2_10-2 88.25474047660828 0.36701497833485974
SignatureGRU-2_10-2 42.80314517021179 0.400196888881004
SignatureLSTM-3-3-3 120.24074339866638 0.4076507900769879
SignatureGRU-3-3-3 62.97554421424866 0.39063779170670887
SignatureLSTM-4-4 96.03213548660278 0.4052757723292336
SignatureGRU-4-4 48.353339195251465 0.3988347368978391
SignatureLSTM-3-3-flatten 130.47794795036316 0.3999453787272458
SignatureGRU-3-3-flatten 44.59340476989746 0.3877476975608165
GRU 19.222602367401123 0.39704690534620724
LSTM 14.720578908920288 0.39139055283364543
GRU-3 24.081738471984863 0.390538225909149
LSTM-3 20.865095376968384 0.3878954360383118
GRU-flatten 17.159971237182617 0.38946798395252924
LSTM-flatten 16.254930019378662 0.38876414894053224
SignatureLSTM-2-2 77.1735029220581 0.4146645218404913
SignatureGRU-2-2 41.82933306694031 0.4113120750069421
SignatureLSTM-3-2 88.85232973098755 0.4072722475261944
SignatureGRU-3-2 54.279431104660034 0.4021511124904409
SignatureLSTM-3-3 82.31147336959839 0.37475666287813514
SignatureGRU-3-3 43.52374482154846 0.405920527014936
SignatureLSTM-2_10-2 84.6880555152893 0.40532694794739077
SignatureGRU-2_10-2 45.60292911529541 0.40049447320938214
SignatureLSTM-3-3-3 123.3988389968872 0.4012446747191487
SignatureGRU-3-3-3 68.68164992332458 0.39099723152222365
SignatureLSTM-4-4 95.26086521148682 0.3798999424138294
SignatureGRU-4-4 52.0423629283905 0.407430108684114
SignatureLSTM-3-3-flatten 127.33495116233826 0.4083989627125141
SignatureGRU-3-3-flatten 46.24544358253479 0.38797832403016386
GRU 20.54114842414856 0.39423622930788305
LSTM 13.889053583145142 0.3778482797708408
GRU-3 21.85821294784546 0.3903126478201936
LSTM-3 21.94953989982605 0.3814775168422788
GRU-flatten 19.477582454681396 0.3890174888289146
LSTM-flatten 21.060513973236084 0.3761563909608875
SignatureLSTM-2-2 82.09768199920654 0.3802706368851472
SignatureGRU-2-2 39.17437410354614 0.38970938256417076
SignatureLSTM-3-2 86.56937623023987 0.4031202174556495
SignatureGRU-3-2 45.77635884284973 0.40550551007061664
SignatureLSTM-3-3 84.72630715370178 0.40299582056082306
SignatureGRU-3-3 46.859670877456665 0.40703021165602393
SignatureLSTM-2_10-2 88.44589233398438 0.400338825875712
SignatureGRU-2_10-2 51.06085658073425 0.4054388493109453
SignatureLSTM-3-3-3 124.37802863121033 0.3965540023258117
SignatureGRU-3-3-3 71.35907530784607 0.40239364755734985
SignatureLSTM-4-4 92.1717689037323 0.4075888768075556
SignatureGRU-4-4 49.61886739730835 0.40894851973628166
SignatureLSTM-3-3-flatten 126.29742479324341 0.40238326750687525
SignatureGRU-3-3-flatten 50.294824838638306 0.40300607914431674
GRU 15.58780026435852 0.39937699813588434
LSTM 16.429083108901978 0.377439307624728
GRU-3 35.42467474937439 0.3759423241391684
LSTM-3 20.71328568458557 0.3748624509877647
GRU-flatten 18.324212312698364 0.39076141453687185
LSTM-flatten 17.83061122894287 0.397213860517341

Model: "SignatureLSTM-2-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_75               │ (None, 45, 100)        │        39,195 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_76               │ (None, 100)            │        63,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_250 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 104,004 (406.27 KB)

 Trainable params: 104,004 (406.27 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-2-2 91.26185083389282 -0.5195619613921447

Model: "SignatureGRU-2-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_75 (SignatureGRU) │ (None, 45, 100)        │        27,195 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_76 (SignatureGRU) │ (None, 100)            │        43,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_253 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 71,904 (280.88 KB)

 Trainable params: 71,904 (280.88 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-2-2 47.337116956710815 0.12761213340898048

Model: "SignatureLSTM-3-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_77               │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_78               │ (None, 100)            │        63,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_256 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 116,504 (455.09 KB)

 Trainable params: 116,504 (455.09 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-2 92.26434278488159 -0.0008917075189957484

Model: "SignatureGRU-3-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_77 (SignatureGRU) │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_78 (SignatureGRU) │ (None, 100)            │        43,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_259 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 84,404 (329.70 KB)

 Trainable params: 84,404 (329.70 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-2 49.64273238182068 0.12448974359612702

Model: "SignatureLSTM-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_79               │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_80               │ (None, 100)            │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_262 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129,004 (503.92 KB)

 Trainable params: 129,004 (503.92 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3 96.93486022949219 -0.02956266388308764

Model: "SignatureGRU-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_79 (SignatureGRU) │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_80 (SignatureGRU) │ (None, 100)            │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_265 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 96,904 (378.53 KB)

 Trainable params: 96,904 (378.53 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3 45.57020425796509 0.11697921573234162

Model: "SignatureLSTM-2_10-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_81               │ (None, 45, 100)        │        47,290 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_82               │ (None, 100)            │        72,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_268 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 120,599 (471.09 KB)

 Trainable params: 120,599 (471.09 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-2_10-2 90.98248386383057 -0.04274463097558154

Model: "SignatureGRU-2_10-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_81 (SignatureGRU) │ (None, 45, 100)        │        35,290 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_82 (SignatureGRU) │ (None, 100)            │        52,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_271 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 88,499 (345.70 KB)

 Trainable params: 88,499 (345.70 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-2_10-2 44.94208359718323 0.12365332120412015

Model: "SignatureLSTM-3-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_83               │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_84               │ (None, 45, 100)        │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_85               │ (None, 100)            │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_274 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 205,404 (802.36 KB)

 Trainable params: 205,404 (802.36 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3-3 129.2499134540558 -0.09961454985311309

Model: "SignatureGRU-3-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_83 (SignatureGRU) │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_84 (SignatureGRU) │ (None, 45, 100)        │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_85 (SignatureGRU) │ (None, 100)            │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_278 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 153,204 (598.45 KB)

 Trainable params: 153,204 (598.45 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3-3 65.40324425697327 0.10780403032719951

Model: "SignatureLSTM-4-4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_86               │ (None, 45, 100)        │       114,195 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_87               │ (None, 100)            │       138,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_282 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 254,004 (992.20 KB)

 Trainable params: 254,004 (992.20 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-4-4 99.40683197975159 -0.1027813845592371

Model: "SignatureGRU-4-4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_86 (SignatureGRU) │ (None, 45, 100)        │       102,195 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_87 (SignatureGRU) │ (None, 100)            │       118,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_285 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 221,904 (866.81 KB)

 Trainable params: 221,904 (866.81 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-4-4 53.70066475868225 0.11211897454652377

Model: "SignatureLSTM-3-3-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_88               │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_89               │ (None, 45, 100)        │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_20 (Flatten)            │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_288 (Dense)               │ (None, 9)              │        40,509 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 168,604 (658.61 KB)

 Trainable params: 168,604 (658.61 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3-flatten 96.22968983650208 0.10744566084959734

Model: "SignatureGRU-3-3-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_88 (SignatureGRU) │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_89 (SignatureGRU) │ (None, 45, 100)        │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_21 (Flatten)            │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_291 (Dense)               │ (None, 9)              │        40,509 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 136,504 (533.22 KB)

 Trainable params: 136,504 (533.22 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3-flatten 44.874804735183716 0.12479854858013624

Model: "GRU"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_35 (GRU)                    │ (None, 45, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_36 (GRU)                    │ (None, 100)            │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_294 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97,809 (382.07 KB)

 Trainable params: 97,809 (382.07 KB)

 Non-trainable params: 0 (0.00 B)

GRU 22.553122758865356 0.0661863669632737

Model: "LSTM"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_35 (LSTM)                  │ (None, 45, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_36 (LSTM)                  │ (None, 100)            │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_295 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129,309 (505.11 KB)

 Trainable params: 129,309 (505.11 KB)

 Non-trainable params: 0 (0.00 B)

LSTM 16.882416486740112 -0.060726883096222255

Model: "GRU-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_37 (GRU)                    │ (None, 45, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_38 (GRU)                    │ (None, 45, 100)        │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_39 (GRU)                    │ (None, 100)            │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_296 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 158,409 (618.79 KB)

 Trainable params: 158,409 (618.79 KB)

 Non-trainable params: 0 (0.00 B)

GRU-3 26.556928396224976 0.0783106127108484

Model: "LSTM-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_37 (LSTM)                  │ (None, 45, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_38 (LSTM)                  │ (None, 45, 100)        │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_39 (LSTM)                  │ (None, 100)            │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_297 (Dense)               │ (None, 9)              │           909 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 209,709 (819.18 KB)

 Trainable params: 209,709 (819.18 KB)

 Non-trainable params: 0 (0.00 B)

LSTM-3 23.618814706802368 0.08281278475894452

Model: "GRU-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_40 (GRU)                    │ (None, 45, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_41 (GRU)                    │ (None, 45, 100)        │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_22 (Flatten)            │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_298 (Dense)               │ (None, 9)              │        40,509 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 137,409 (536.75 KB)

 Trainable params: 137,409 (536.75 KB)

 Non-trainable params: 0 (0.00 B)

GRU-flatten 21.504854679107666 0.07344422214571802

Model: "LSTM-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_40 (LSTM)                  │ (None, 45, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_41 (LSTM)                  │ (None, 45, 100)        │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_23 (Flatten)            │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_299 (Dense)               │ (None, 9)              │        40,509 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 168,909 (659.80 KB)

 Trainable params: 168,909 (659.80 KB)

 Non-trainable params: 0 (0.00 B)

LSTM-flatten 17.166560649871826 -0.22951193530239225
SignatureLSTM-2-2 88.923264503479 -0.10293846581914898
SignatureGRU-2-2 47.863208532333374 0.10691339301631311
SignatureLSTM-3-2 88.20916795730591 0.015002952960392137
SignatureGRU-3-2 48.6265435218811 0.11951511114136294
SignatureLSTM-3-3 86.15741014480591 -0.067309209673103
SignatureGRU-3-3 45.51351737976074 0.1254590936916478
SignatureLSTM-2_10-2 84.3509533405304 -0.1782183300784031
SignatureGRU-2_10-2 48.7425696849823 0.12673623006331702
SignatureLSTM-3-3-3 124.14752459526062 -0.13744411260362244
SignatureGRU-3-3-3 65.89492917060852 0.11408419419873578
SignatureLSTM-4-4 92.24965023994446 -0.07440972507624105
SignatureGRU-4-4 53.9790940284729 0.11940469586479442
SignatureLSTM-3-3-flatten 83.4308819770813 0.07547588512933233
SignatureGRU-3-3-flatten 44.20241332054138 0.12082982750959996
GRU 17.972166538238525 0.10531455793492878
LSTM 17.065598964691162 -0.3066950389809036
GRU-3 22.32645893096924 0.12758458321901953
LSTM-3 22.296277046203613 0.0038726814528074905
GRU-flatten 19.19807529449463 0.10569700590533543
LSTM-flatten 21.672231435775757 -0.6728056558415335
SignatureLSTM-2-2 76.4482638835907 -0.02248053702013418
SignatureGRU-2-2 50.93354344367981 0.10711946637194718
SignatureLSTM-3-2 83.68099474906921 -0.007336421850288414
SignatureGRU-3-2 53.489887714385986 0.11447770765707722
SignatureLSTM-3-3 82.15507984161377 -0.16125111969451905
SignatureGRU-3-3 47.928075551986694 0.10906052690183304
SignatureLSTM-2_10-2 84.272531747818 -0.07729660085672095
SignatureGRU-2_10-2 49.53576588630676 0.09951638802913962
SignatureLSTM-3-3-3 129.0355498790741 -0.5820890723420585
SignatureGRU-3-3-3 63.01423168182373 0.13070931145304382
SignatureLSTM-4-4 92.02996802330017 -0.06463990656390448
SignatureGRU-4-4 59.10983109474182 0.12024161560508954
SignatureLSTM-3-3-flatten 89.19553852081299 0.09580274916875611
SignatureGRU-3-3-flatten 44.71233868598938 0.10191047142942013
GRU 18.495280265808105 0.09275639142019827
LSTM 19.956600427627563 -0.004832071773704618
GRU-3 30.913602590560913 0.06281388685323248
LSTM-3 23.610899209976196 -0.2091858974819799
GRU-flatten 20.313584804534912 0.09400369467276028
LSTM-flatten 16.962151765823364 -0.12852798560030088
SignatureLSTM-2-2 74.36693406105042 0.06488432727768657
SignatureGRU-2-2 46.07651472091675 0.11964271925377165
SignatureLSTM-3-2 86.13400101661682 -0.10504074254084649
SignatureGRU-3-2 52.6533260345459 0.12093174496669806
SignatureLSTM-3-3 85.63412141799927 -0.15398432391620187
SignatureGRU-3-3 43.14576530456543 0.13204048113354908
SignatureLSTM-2_10-2 92.96454071998596 -0.3730844716841377
SignatureGRU-2_10-2 46.26888680458069 0.1333700796004614
SignatureLSTM-3-3-3 127.26137375831604 -0.15610940882238122
SignatureGRU-3-3-3 55.82221031188965 0.124119131702566
SignatureLSTM-4-4 95.91081738471985 -0.3093734721236135
SignatureGRU-4-4 49.34599041938782 0.12413664439095548
SignatureLSTM-3-3-flatten 80.95126605033875 0.10167879621865666
SignatureGRU-3-3-flatten 49.974873781204224 0.10504979795431743
GRU 16.393174409866333 0.13123801704225013
LSTM 19.044254064559937 0.06280305616678608
GRU-3 24.378785133361816 0.07455766092230946
LSTM-3 23.295324563980103 -0.21588625412667856
GRU-flatten 21.134830713272095 0.0879362919000322
LSTM-flatten 16.360450506210327 -0.06629517943474267
SignatureLSTM-2-2 81.57249879837036 -0.09276388334280122
SignatureGRU-2-2 46.647351026535034 0.13020573512168424
SignatureLSTM-3-2 83.26371359825134 -0.10114774029452364
SignatureGRU-3-2 55.473388671875 0.10243278816964582
SignatureLSTM-3-3 88.02354216575623 -0.26727241979910094
SignatureGRU-3-3 51.99488282203674 0.12159317489203891
SignatureLSTM-2_10-2 84.37006425857544 -0.07716198142298707
SignatureGRU-2_10-2 47.03379583358765 0.12024224197697074
SignatureLSTM-3-3-3 122.31679153442383 -0.4597021857214949
SignatureGRU-3-3-3 60.67853355407715 0.11577342295102871
SignatureLSTM-4-4 88.23319888114929 -0.06266167665533445
SignatureGRU-4-4 53.61184000968933 0.12208279155611618
SignatureLSTM-3-3-flatten 87.30959868431091 0.00707694068058446
SignatureGRU-3-3-flatten 43.98457741737366 0.11529894325635784
GRU 20.55035901069641 0.07922378286750095
LSTM 19.345988035202026 -0.15733406572654537
GRU-3 28.596323490142822 -0.03615405148410447
LSTM-3 27.215400218963623 0.007599217937777613
GRU-flatten 21.87047815322876 0.08421757514677079
LSTM-flatten 16.333386182785034 -0.0762804646483013

Model: "SignatureLSTM-2-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_150              │ (None, 75, 100)        │        39,195 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_151              │ (None, 100)            │        63,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_500 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 104,610 (408.63 KB)

 Trainable params: 104,610 (408.63 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-2-2 156.3634512424469 -0.015942299522822143

Model: "SignatureGRU-2-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_150               │ (None, 75, 100)        │        27,195 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_151               │ (None, 100)            │        43,800 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_503 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 72,510 (283.24 KB)

 Trainable params: 72,510 (283.24 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-2-2 49.80920100212097 0.09653409730004017

Model: "SignatureLSTM-3-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_152              │ (None, 75, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_153              │ (None, 100)            │        63,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_506 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 117,110 (457.46 KB)

 Trainable params: 117,110 (457.46 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-2 165.96968579292297 0.025906229097853214

Model: "SignatureGRU-3-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_152               │ (None, 75, 100)        │        39,695 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_153               │ (None, 100)            │        43,800 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_509 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 85,010 (332.07 KB)

 Trainable params: 85,010 (332.07 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-2 60.172561168670654 0.0683923689034918

Model: "SignatureLSTM-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_154              │ (None, 75, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_155              │ (None, 100)            │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_512 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129,610 (506.29 KB)

 Trainable params: 129,610 (506.29 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3 162.1404402256012 0.03381710735053243

Model: "SignatureGRU-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_154               │ (None, 75, 100)        │        39,695 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_155               │ (None, 100)            │        56,300 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_515 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97,510 (380.90 KB)

 Trainable params: 97,510 (380.90 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3 55.16925001144409 0.0885997378112434

Model: "SignatureLSTM-2_10-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_156              │ (None, 75, 100)        │        47,290 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_157              │ (None, 100)            │        72,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_518 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 121,205 (473.46 KB)

 Trainable params: 121,205 (473.46 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-2_10-2 164.3609640598297 -0.06653176818631523

Model: "SignatureGRU-2_10-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_156               │ (None, 75, 100)        │        35,290 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_157               │ (None, 100)            │        52,300 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_521 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 89,105 (348.07 KB)

 Trainable params: 89,105 (348.07 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-2_10-2 46.885608434677124 0.09003240557449375

Model: "SignatureLSTM-3-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_158              │ (None, 75, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_159              │ (None, 75, 100)        │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_160              │ (None, 100)            │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_524 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 206,010 (804.73 KB)

 Trainable params: 206,010 (804.73 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3-3 221.43537139892578 -0.14530013897059224

Model: "SignatureGRU-3-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_158               │ (None, 75, 100)        │        39,695 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_159               │ (None, 75, 100)        │        56,300 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_160               │ (None, 100)            │        56,300 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_528 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 153,810 (600.82 KB)

 Trainable params: 153,810 (600.82 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3-3 77.56500172615051 0.07197759424215364

Model: "SignatureLSTM-4-4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_161              │ (None, 75, 100)        │       114,195 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_162              │ (None, 100)            │       138,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_532 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 254,610 (994.57 KB)

 Trainable params: 254,610 (994.57 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-4-4 183.70684218406677 0.03883941321673605

Model: "SignatureGRU-4-4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_161               │ (None, 75, 100)        │       102,195 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_162               │ (None, 100)            │       118,800 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_535 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 222,510 (869.18 KB)

 Trainable params: 222,510 (869.18 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-4-4 67.36417150497437 0.09010038136561814

Model: "SignatureLSTM-3-3-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_163              │ (None, 75, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_164              │ (None, 75, 100)        │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_40 (Flatten)            │ (None, 7500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_538 (Dense)               │ (None, 15)             │       112,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 240,610 (939.88 KB)

 Trainable params: 240,610 (939.88 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3-flatten 166.32950615882874 -0.03538315137525845

Model: "SignatureGRU-3-3-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_163               │ (None, 75, 100)        │        39,695 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_164               │ (None, 75, 100)        │        56,300 │
│ (SignatureGRU)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_41 (Flatten)            │ (None, 7500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_541 (Dense)               │ (None, 15)             │       112,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 208,510 (814.49 KB)

 Trainable params: 208,510 (814.49 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3-flatten 58.477033376693726 0.04445182002453322

Model: "GRU"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_70 (GRU)                    │ (None, 75, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_71 (GRU)                    │ (None, 100)            │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_544 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 98,415 (384.43 KB)

 Trainable params: 98,415 (384.43 KB)

 Non-trainable params: 0 (0.00 B)

GRU 23.391201496124268 0.10474748749475862

Model: "LSTM"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_70 (LSTM)                  │ (None, 75, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_71 (LSTM)                  │ (None, 100)            │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_545 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129,915 (507.48 KB)

 Trainable params: 129,915 (507.48 KB)

 Non-trainable params: 0 (0.00 B)

LSTM 20.919419288635254 -0.04294361705921355

Model: "GRU-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_72 (GRU)                    │ (None, 75, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_73 (GRU)                    │ (None, 75, 100)        │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_74 (GRU)                    │ (None, 100)            │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_546 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 159,015 (621.15 KB)

 Trainable params: 159,015 (621.15 KB)

 Non-trainable params: 0 (0.00 B)

GRU-3 43.37559413909912 0.0028975108025063607

Model: "LSTM-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_72 (LSTM)                  │ (None, 75, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_73 (LSTM)                  │ (None, 75, 100)        │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_74 (LSTM)                  │ (None, 100)            │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_547 (Dense)               │ (None, 15)             │         1,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 210,315 (821.54 KB)

 Trainable params: 210,315 (821.54 KB)

 Non-trainable params: 0 (0.00 B)

LSTM-3 30.020593404769897 -0.08618669674106029

Model: "GRU-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_75 (GRU)                    │ (None, 75, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_76 (GRU)                    │ (None, 75, 100)        │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_42 (Flatten)            │ (None, 7500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_548 (Dense)               │ (None, 15)             │       112,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 209,415 (818.03 KB)

 Trainable params: 209,415 (818.03 KB)

 Non-trainable params: 0 (0.00 B)

GRU-flatten 30.716849088668823 0.07457579841353953

Model: "LSTM-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_75 (LSTM)                  │ (None, 75, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_76 (LSTM)                  │ (None, 75, 100)        │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_43 (Flatten)            │ (None, 7500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_549 (Dense)               │ (None, 15)             │       112,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 240,915 (941.07 KB)

 Trainable params: 240,915 (941.07 KB)

 Non-trainable params: 0 (0.00 B)

LSTM-flatten 25.778358936309814 -0.07164864160467133
SignatureLSTM-2-2 152.25447726249695 -0.20583844289233297
SignatureGRU-2-2 47.90111017227173 0.08678455980908338
SignatureLSTM-3-2 164.1695601940155 0.03519959321711041
SignatureGRU-3-2 52.681005001068115 0.09029310869991987
SignatureLSTM-3-3 163.9694049358368 -0.3028076918590596
SignatureGRU-3-3 53.609349727630615 0.10665523073627127
SignatureLSTM-2_10-2 158.5475878715515 -0.007850778342179888
SignatureGRU-2_10-2 53.50399374961853 0.08528956761561576
SignatureLSTM-3-3-3 225.8143060207367 -0.12918326813272715
SignatureGRU-3-3-3 86.92336177825928 0.076872204450145
SignatureLSTM-4-4 176.18883061408997 -0.05816720337960355
SignatureGRU-4-4 58.967583894729614 0.09836824118303468
SignatureLSTM-3-3-flatten 166.4694585800171 0.059410151698047156
SignatureGRU-3-3-flatten 60.9447386264801 0.07506096279492562
GRU 32.36137628555298 -0.0013301901890998113
LSTM 20.942839860916138 -0.07327858134268622
GRU-3 33.38113212585449 0.10515711774143886
LSTM-3 29.902286767959595 -0.21139048164897759
GRU-flatten 25.044618606567383 0.07737896601836076
LSTM-flatten 23.787810564041138 -0.083214249339075
SignatureLSTM-2-2 154.30658745765686 -0.014819353610363994
SignatureGRU-2-2 50.850921869277954 0.09518825161507621
SignatureLSTM-3-2 155.5878508090973 -0.2630237177436925
SignatureGRU-3-2 60.13253712654114 0.08245229309721361
SignatureLSTM-3-3 158.27561283111572 -0.330987780458207
SignatureGRU-3-3 56.07524490356445 0.0990024356812724
SignatureLSTM-2_10-2 150.82856154441833 -0.2615223920204786
SignatureGRU-2_10-2 55.7640426158905 0.0886220845905022
SignatureLSTM-3-3-3 210.36854815483093 -0.17317461270854292
SignatureGRU-3-3-3 83.27683281898499 0.08858034664221696
SignatureLSTM-4-4 171.13931274414062 -0.06343691473151095
SignatureGRU-4-4 63.44303035736084 0.09488105417528506
SignatureLSTM-3-3-flatten 160.2688753604889 0.037526594215756555
SignatureGRU-3-3-flatten 53.348421573638916 0.07314480042764067
GRU 22.805293560028076 0.1041481272923947
LSTM 25.525587558746338 -0.42844028253681804
GRU-3 42.99584722518921 0.012214403753408935
LSTM-3 31.28537893295288 -0.19895911873345717
GRU-flatten 26.61599636077881 0.08322286667634349
LSTM-flatten 20.913570165634155 -0.02579800784304428
SignatureLSTM-2-2 154.39258241653442 -0.23337137507121128
SignatureGRU-2-2 51.34198188781738 0.10053247948803401
SignatureLSTM-3-2 160.41294741630554 -0.04741359782487478
SignatureGRU-3-2 60.23402523994446 0.08628497845019065
SignatureLSTM-3-3 159.30903220176697 -0.12076660597987209
SignatureGRU-3-3 47.22785782814026 0.09197533062480044
SignatureLSTM-2_10-2 152.71739149093628 -0.1246117345771536
SignatureGRU-2_10-2 50.43497395515442 0.08956366725222589
SignatureLSTM-3-3-3 208.02430081367493 -0.2102356952531054
SignatureGRU-3-3-3 69.92654991149902 0.08681906228057228
SignatureLSTM-4-4 169.87150955200195 -0.1344517369272463
SignatureGRU-4-4 68.9750657081604 0.08547098281576544
SignatureLSTM-3-3-flatten 162.88125872612 -0.0055177923907384924
SignatureGRU-3-3-flatten 63.77937579154968 0.078684436797197
GRU 24.030773639678955 0.09689823962431034
LSTM 20.818040370941162 -0.13367244293543581
GRU-3 36.40937256813049 0.0809179088738509
LSTM-3 29.77908945083618 -0.18919539518795028
GRU-flatten 29.368770837783813 0.07243719786388843
LSTM-flatten 30.707308053970337 -1.3049861950299075
SignatureLSTM-2-2 152.95978617668152 -0.06590100996906781
SignatureGRU-2-2 51.64335489273071 0.09275266502950326
SignatureLSTM-3-2 152.02197909355164 0.05116238880780193
SignatureGRU-3-2 58.869900941848755 0.08928264584365625
SignatureLSTM-3-3 158.73892784118652 -0.022177542617181523
SignatureGRU-3-3 52.91372847557068 0.095350756015763
SignatureLSTM-2_10-2 153.06522297859192 -0.16724845987264866
SignatureGRU-2_10-2 53.512550830841064 0.09673364030355211
SignatureLSTM-3-3-3 211.1463439464569 0.0031632091590022855
SignatureGRU-3-3-3 73.82157516479492 0.0756411472654726
SignatureLSTM-4-4 170.0111608505249 -0.17248762317057953
SignatureGRU-4-4 66.94658350944519 0.0766496122191488
SignatureLSTM-3-3-flatten 158.52299094200134 -0.06944204501189871
SignatureGRU-3-3-flatten 61.46388649940491 0.0633889664489314
GRU 22.613821983337402 0.09920893546103193
LSTM 21.522897720336914 -0.18064411199741112
GRU-3 52.713308811187744 -0.07457982541248913
LSTM-3 31.4595148563385 -0.13650760377545168
GRU-flatten 32.58268094062805 0.0719730050232704
LSTM-flatten 25.69223403930664 -0.3428434921732458
R2 scores
Means:

,SignatureLSTM-2-2,SignatureGRU-2-2,SignatureLSTM-3-2,SignatureGRU-3-2,SignatureLSTM-3-3,SignatureGRU-3-3,SignatureLSTM-2_10-2,SignatureGRU-2_10-2,SignatureLSTM-3-3-3,SignatureGRU-3-3-3,SignatureLSTM-4-4,SignatureGRU-4-4,SignatureLSTM-3-3-flatten,SignatureGRU-3-3-flatten,GRU,LSTM,GRU-3,LSTM-3,GRU-flatten,LSTM-flatten
1,0.393137,0.399465,0.400994,0.402904,0.399580,0.405062,0.389849,0.404076,0.402455,0.394087,0.395625,0.404248,0.403768,0.393307,0.397250,0.384692,0.383988,0.369952,0.387848,0.386061
9,-0.134572,0.118299,-0.039883,0.116369,-0.135876,0.121026,-0.149701,0.120704,-0.286992,0.118498,-0.122773,0.119597,0.077496,0.113578,0.094944,-0.093357,0.061423,-0.066157,0.089060,-0.234684
15,-0.107174,0.094358,-0.039634,0.083341,-0.148585,0.096317,-0.125553,0.090048,-0.130946,0.079978,-0.077941,0.089094,-0.002681,0.066946,0.080735,-0.171796,0.025321,-0.164448,0.075918,-0.365698

,SignatureLSTM-2-2,SignatureGRU-2-2,SignatureLSTM-3-2,SignatureGRU-3-2,SignatureLSTM-3-3,SignatureGRU-3-3,SignatureLSTM-2_10-2,SignatureGRU-2_10-2,SignatureLSTM-3-3-3,SignatureGRU-3-3-3,SignatureLSTM-4-4,SignatureGRU-4-4,SignatureLSTM-3-3-flatten,SignatureGRU-3-3-flatten,GRU,LSTM,GRU-3,LSTM-3,GRU-flatten,LSTM-flatten
1,0.055175,0.054891,0.054821,0.054734,0.054883,0.054635,0.055326,0.054681,0.054755,0.055137,0.055065,0.054672,0.054695,0.055172,0.054993,0.055562,0.055594,0.056217,0.055420,0.055500
9,0.074926,0.066392,0.072038,0.066465,0.075169,0.066303,0.075596,0.066308,0.079647,0.066399,0.074768,0.066358,0.067902,0.066581,0.067237,0.073672,0.068439,0.072810,0.067477,0.078141
15,0.074641,0.067625,0.072282,0.068036,0.075890,0.067552,0.075250,0.067789,0.075378,0.068179,0.073670,0.067823,0.071132,0.068648,0.068093,0.076738,0.070078,0.076640,0.068297,0.081887

Std:

,SignatureLSTM-2-2,SignatureGRU-2-2,SignatureLSTM-3-2,SignatureGRU-3-2,SignatureLSTM-3-3,SignatureGRU-3-3,SignatureLSTM-2_10-2,SignatureGRU-2_10-2,SignatureLSTM-3-3-3,SignatureGRU-3-3-3,SignatureLSTM-4-4,SignatureGRU-4-4,SignatureLSTM-3-3-flatten,SignatureGRU-3-3-flatten,GRU,LSTM,GRU-3,LSTM-3,GRU-flatten,LSTM-flatten
1,0.017137,0.007043,0.005855,0.003245,0.013586,0.001924,0.013236,0.003651,0.003630,0.004506,0.010070,0.004756,0.002765,0.005555,0.001772,0.006063,0.007904,0.021212,0.002615,0.007131
9,0.201650,0.009848,0.052136,0.007674,0.082754,0.007757,0.120547,0.011442,0.195712,0.008025,0.094394,0.004078,0.036824,0.008835,0.022377,0.128758,0.053588,0.122811,0.010675,0.226580
15,0.094039,0.004549,0.116707,0.007957,0.146341,0.006220,0.086677,0.003731,0.072477,0.006531,0.072624,0.007596,0.046918,0.012335,0.041139,0.136899,0.063434,0.046717,0.004123,0.482613

,SignatureLSTM-2-2,SignatureGRU-2-2,SignatureLSTM-3-2,SignatureGRU-3-2,SignatureLSTM-3-3,SignatureGRU-3-3,SignatureLSTM-2_10-2,SignatureGRU-2_10-2,SignatureLSTM-3-3-3,SignatureGRU-3-3-3,SignatureLSTM-4-4,SignatureGRU-4-4,SignatureLSTM-3-3-flatten,SignatureGRU-3-3-flatten,GRU,LSTM,GRU-3,LSTM-3,GRU-flatten,LSTM-flatten
1,0.000779,0.000322,0.000267,0.000149,0.000618,0.000088,0.000598,0.000168,0.000166,0.000205,0.000458,0.000218,0.000127,0.000253,0.000081,0.000274,0.000356,0.000936,0.000118,0.000322
9,0.006356,0.000367,0.001794,0.000289,0.002674,0.000281,0.003834,0.000420,0.005817,0.000297,0.003078,0.000148,0.001331,0.000324,0.000817,0.004228,0.001883,0.004107,0.000387,0.006687
15,0.003097,0.000165,0.003854,0.000289,0.004757,0.000242,0.002840,0.000140,0.002380,0.000236,0.002462,0.000279,0.001660,0.000442,0.001483,0.004287,0.002246,0.001541,0.000150,0.013320

Training Times

,SignatureLSTM-2-2,SignatureGRU-2-2,SignatureLSTM-3-2,SignatureGRU-3-2,SignatureLSTM-3-3,SignatureGRU-3-3,SignatureLSTM-2_10-2,SignatureGRU-2_10-2,SignatureLSTM-3-3-3,SignatureGRU-3-3-3,SignatureLSTM-4-4,SignatureGRU-4-4,SignatureLSTM-3-3-flatten,SignatureGRU-3-3-flatten,GRU,LSTM,GRU-3,LSTM-3,GRU-flatten,LSTM-flatten
1,82.656979,41.744139,85.626511,47.768060,86.771965,43.893235,89.371870,46.291192,122.443510,66.963048,97.229167,51.152382,128.537148,48.967095,19.077594,14.706821,28.582612,22.822792,18.777823,18.310477
9,82.514562,47.771547,86.710444,51.977176,87.781003,46.830489,87.388115,47.304620,126.402231,62.162630,93.566093,53.949484,87.423395,45.549802,19.192821,18.458972,26.554420,24.007343,20.804365,17.698956
15,154.055377,50.309314,159.632405,58.418006,160.486684,52.999086,155.903946,52.020234,215.357774,78.302664,174.183531,65.139287,162.894418,59.602691,25.040493,21.945757,41.775051,30.489373,28.865783,25.375856

,SignatureLSTM-2-2,SignatureGRU-2-2,SignatureLSTM-3-2,SignatureGRU-3-2,SignatureLSTM-3-3,SignatureGRU-3-3,SignatureLSTM-2_10-2,SignatureGRU-2_10-2,SignatureLSTM-3-3-3,SignatureGRU-3-3-3,SignatureLSTM-4-4,SignatureGRU-4-4,SignatureLSTM-3-3-flatten,SignatureGRU-3-3-flatten,GRU,LSTM,GRU-3,LSTM-3,GRU-flatten,LSTM-flatten
1,3.126633,2.326170,4.308339,3.692054,4.252355,1.548704,4.234455,2.878468,3.294972,3.521717,3.624107,2.072887,2.312145,3.682688,2.403916,0.904345,5.240006,2.129134,1.091168,2.609470
9,6.658195,1.693063,3.300962,2.515764,4.954757,2.992510,3.796205,1.659722,2.740668,3.675876,3.798537,3.098326,5.263704,2.236229,2.142387,1.248940,3.025918,1.675379,0.954727,2.013436
15,1.410502,1.355652,5.208323,2.913191,2.199755,3.093837,4.949384,3.076429,6.966844,6.161856,5.291203,3.574824,3.180684,3.552262,3.693775,1.806929,6.677514,0.727149,2.726082,3.197511