In [1]:
!pip install pandas numpy matplotlib pyarrow scikit-learn tkan "jax[cuda12]" keras_sig tkan sig_rnn --upgrade

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (2.2.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.10.0)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.10/dist-packages (18.1.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.6.0)
Requirement already satisfied: tkan in /usr/local/lib/python3.10/dist-packages (0.4.3)
Requirement already satisfied: jax[cuda12] in /usr/local/lib/python3.10/dist-packages (0.4.38)
Requirement already satisfied: keras_sig in /usr/local/lib/python3.10/dist-packages (1.0.2)
Requirement already satisfied: sig_rnn in /usr/local/lib/python3.10/dist-packages (0.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib) (2.4.7)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.8)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (11.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.3.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.55.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: keras<4.0.0,>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from tkan) (3.7.0)
Requirement already satisfied: keras_efficient_kan<0.2.0,>=0.1.9 in /usr/local/lib/python3.10/dist-packages (from tkan) (0.1.10)
Requirement already satisfied: jaxlib<=0.4.38,>=0.4.38 in /usr/local/lib/python3.10/dist-packages (from jax[cuda12]) (0.4.38)
Requirement already satisfied: ml_dtypes>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from jax[cuda12]) (0.5.0)
Requirement already satisfied: opt_einsum in /usr/local/lib/python3.10/dist-packages (from jax[cuda12]) (3.4.0)
Requirement already satisfied: jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38 in /usr/local/lib/python3.10/dist-packages (from jax[cuda12]) (0.4.38)
Requirement already satisfied: jaxtyping<0.3.0,>=0.2.36 in /usr/local/lib/python3.10/dist-packages (from keras_sig) (0.2.36)
Requirement already satisfied: jax-cuda12-pjrt==0.4.38 in /usr/local/lib/python3.10/dist-packages (from jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38->jax[cuda12]) (0.4.38)
Requirement already satisfied: nvidia-cusparse-cu12>=12.1.0.106 in /usr/local/lib/python3.10/dist-packages (from jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38->jax[cuda12]) (12.5.4.2)
Requirement already satisfied: nvidia-cudnn-cu12<10.0,>=9.1 in /usr/local/lib/python3.10/dist-packages (from jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38->jax[cuda12]) (9.6.0.74)
Requirement already satisfied: nvidia-cuda-runtime-cu12>=12.1.105 in /usr/local/lib/python3.10/dist-packages (from jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38->jax[cuda12]) (12.6.77)
Requirement already satisfied: nvidia-cusolver-cu12>=11.4.5.107 in /usr/local/lib/python3.10/dist-packages (from jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38->jax[cuda12]) (11.7.1.2)
Requirement already satisfied: nvidia-nvjitlink-cu12>=12.1.105 in /usr/local/lib/python3.10/dist-packages (from jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38->jax[cuda12]) (12.6.85)
Requirement already satisfied: nvidia-cuda-cupti-cu12>=12.1.105 in /usr/local/lib/python3.10/dist-packages (from jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38->jax[cuda12]) (12.6.80)
Requirement already satisfied: nvidia-nccl-cu12>=2.18.1 in /usr/local/lib/python3.10/dist-packages (from jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38->jax[cuda12]) (2.23.4)
Requirement already satisfied: nvidia-cublas-cu12>=12.1.3.1 in /usr/local/lib/python3.10/dist-packages (from jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38->jax[cuda12]) (12.6.4.1)
Requirement already satisfied: nvidia-cuda-nvcc-cu12>=12.6.85 in /usr/local/lib/python3.10/dist-packages (from jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38->jax[cuda12]) (12.6.85)
Requirement already satisfied: nvidia-cufft-cu12>=11.0.2.54 in /usr/local/lib/python3.10/dist-packages (from jax-cuda12-plugin[with_cuda]<=0.4.38,>=0.4.38->jax[cuda12]) (11.3.0.4)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from keras<4.0.0,>=3.0.0->tkan) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.10/dist-packages (from keras<4.0.0,>=3.0.0->tkan) (0.0.8)
Requirement already satisfied: h5py in /usr/local/lib/python3.10/dist-packages (from keras<4.0.0,>=3.0.0->tkan) (3.12.1)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from keras<4.0.0,>=3.0.0->tkan) (2.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.10/dist-packages (from keras<4.0.0,>=3.0.0->tkan) (0.13.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.10/dist-packages (from optree->keras<4.0.0,>=3.0.0->tkan) (4.12.2)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras<4.0.0,>=3.0.0->tkan) (2.18.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras<4.0.0,>=3.0.0->tkan) (3.0.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->keras<4.0.0,>=3.0.0->tkan) (0.1.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

# Exploring Signature-Based Gating in LSTM and GRU Networks

This notebook investigates the integration of path signatures into classical recurrent neural network architectures, focusing on their application in gating mechanisms. We explore two different approaches:

1. **Signature-Based LSTM**: A modified LSTM where the forget gate is controlled by path signatures instead of traditional linear transformations, while maintaining the standard computation for input and output gates.

2. **Signature-Based GRU**: An adaptation of the Gated Recurrent Unit where the reset gate computation is enhanced with path signatures, preserving the original update gate mechanics.

## Motivation

Traditional LSTM and GRU architectures use linear transformations followed by nonlinear activations for their gating mechanisms. However, path signatures provide a rich, hierarchical representation of sequential data that could potentially offer more sophisticated control over information flow in these networks. By incorporating signatures into specific gating mechanisms, we aim to:

- Capture higher-order temporal patterns in the input sequences
- Provide better control over long-term dependencies through signature-based forget/reset mechanisms
- Maintain the proven effectiveness of standard gates while enhancing critical gates with signature computations

## Implementation Details

The notebook implements these architectures using Keras 3's backend-agnostic framework, ensuring compatibility across TensorFlow, JAX, and PyTorch backends. Each implementation:
- Uses streaming signatures to maintain temporal coherence
- Normalizes signature values by sequence length
- Maintains the original architecture's core functionality while enhancing specific gates
- Computes signatures at the RNN level to optimize computational efficiency

## Usage

The implementations can be used as drop-in replacements for standard LSTM and GRU layers in any Keras model. They accept the same input formats and provide the same output structures as their traditional counterparts.

---

*Note: This research explores the potential benefits of combining classical RNN architectures with modern signature methods for enhanced temporal data processing.*

In [2]:
import os
BACKEND = 'jax' # You can use any backend here 
os.environ['KERAS_BACKEND'] = BACKEND

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import keras
from keras.models import Sequential
from keras.layers import LSTM, Dense, Input, Flatten, GRU

from sklearn.metrics import r2_score
from sklearn.metrics import root_mean_squared_error

from tkan import TKAN
from keras_sig import SigLayer

from sig_rnn import SignatureGRU,SignatureLSTM

import time

keras.utils.set_random_seed(1) 

N_MAX_EPOCHS = 1000
BATCH_SIZE = 128
early_stopping_callback = lambda : keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.00001,
    patience=10,
    mode="min",
    restore_best_weights=True,
    start_from_epoch=6,
)
lr_callback = lambda : keras.callbacks.ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.25,
    patience=5,
    mode="min",
    min_delta=0.00001,
    min_lr=0.000025,
    verbose=0,
)
callbacks = lambda : [early_stopping_callback(), lr_callback(), keras.callbacks.TerminateOnNaN()]

# Data

In [3]:
df = pd.read_parquet('data.parquet')
df = df[(df.index >= pd.Timestamp('2020-01-01')) & (df.index < pd.Timestamp('2023-01-01'))]
assets = ['BTC', 'ETH', 'ADA', 'XMR', 'EOS', 'MATIC', 'TRX', 'FTM', 'BNB', 'XLM', 'ENJ', 'CHZ', 'BUSD', 'ATOM', 'LINK', 'ETC', 'XRP', 'BCH', 'LTC']
df = df[[c for c in df.columns if 'close' in c and any(asset in c for asset in assets)]]
df.columns = [c.replace(' close', '') for c in df.columns]
df = np.sqrt((df / df.shift() - 1.).dropna() ** 2)
display(df)

,BTC,ADA,XMR,EOS,CHZ,MATIC,TRX,ENJ,FTM,BNB,XLM,BUSD,ATOM,LTC,LINK,ETC,ETH,XRP,BCH
group,,,,,,,,,,,,,,,,,,,
2020-01-01 01:00:00,0.005469,0.006406,0.006955,0.010780,0.013347,0.003613,0.010574,0.000499,0.000000,0.007402,0.006462,0.000399,0.017070,0.008236,0.010942,0.009307,0.013735,0.006390,0.008609
2020-01-01 02:00:00,0.003683,0.005456,0.003119,0.002370,0.002242,0.007199,0.002242,0.007984,0.005525,0.003500,0.001328,0.000000,0.009324,0.005526,0.009702,0.006376,0.001607,0.002426,0.005771
2020-01-01 03:00:00,0.002463,0.004221,0.000444,0.005263,0.000979,0.007863,0.008949,0.012575,0.000916,0.002224,0.001327,0.000100,0.003464,0.007646,0.003999,0.008089,0.004968,0.001081,0.008053
2020-01-01 04:00:00,0.001071,0.001211,0.003774,0.003067,0.000419,0.002882,0.000752,0.000869,0.006416,0.001795,0.001328,0.000399,0.002317,0.001445,0.002008,0.001282,0.000000,0.001753,0.002382
2020-01-01 05:00:00,0.000962,0.003334,0.000000,0.000459,0.000838,0.001437,0.000000,0.009198,0.000923,0.000616,0.000665,0.000000,0.004413,0.004568,0.003506,0.000530,0.000768,0.003409,0.001649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-31 19:00:00,0.000461,0.005663,0.004073,0.003472,0.002985,0.004732,0.001101,0.004141,0.002003,0.001217,0.000000,0.000000,0.000214,0.003146,0.003953,0.000633,0.002543,0.003514,0.000000
2022-12-31 20:00:00,0.000093,0.002011,0.000000,0.002307,0.000992,0.000916,0.000183,0.001237,0.000500,0.000000,0.004219,0.000100,0.001391,0.003421,0.000179,0.003802,0.000258,0.000584,0.004115
2022-12-31 21:00:00,0.001226,0.004817,0.002028,0.003452,0.003972,0.004190,0.000733,0.004942,0.003996,0.000405,0.001401,0.000100,0.002884,0.002273,0.003759,0.005682,0.001863,0.002625,0.004098
2022-12-31 22:00:00,0.001660,0.006858,0.008097,0.004619,0.002991,0.005260,0.003480,0.004553,0.000502,0.002834,0.002805,0.000000,0.003428,0.001993,0.000180,0.004444,0.003258,0.003801,0.001029
2022-12-31 23:00:00,0.001307,0.001625,0.002041,0.000000,0.003000,0.002379,0.001838,0.001247,0.001504,0.000000,0.001406,0.000100,0.005375,0.000713,0.001617,0.000638,0.000050,0.005283,0.001030

In [4]:
def generate_data(df, sequence_length, n_ahead):
    #Case without known inputs

    tmp_df = df.copy() #/ scaler_df
    def prepare_sequences(df, n_history, n_future):
        X, y = [], []
        num_features = df.shape[1]
        
        # Iterate through the DataFrame to create sequences
        for i in range(n_history, len(df) - n_future + 1):
            # Extract the sequence of past observations
            X.append(df.iloc[i - n_history:i].values)
            # Extract the future values of the first column
            y.append(df.iloc[i:i + n_future,0].values)
           
        return np.array(X), np.array(y)
    
    # Prepare sequences
    X, y = prepare_sequences(tmp_df, sequence_length, n_ahead)
    
    # Split the dataset into training and testing sets
    train_test_separation = int(len(X) * 0.8)
    X_train, X_test = X[:train_test_separation], X[train_test_separation:]
    y_train, y_test = y[:train_test_separation], y[train_test_separation:]

    max_X_train = np.max(X_train, axis=0)
    X_train /= max_X_train
    X_test /= max_X_train

    max_y_train = np.max(y_train, axis=0)
    y_train /= max_y_train
    y_test /= max_y_train
    
    y_train = y_train.reshape(y_train.shape[0], -1) 
    y_test = y_test.reshape(y_test.shape[0], -1)
    return X_train, X_test, y_train, y_test

In [5]:
n_aheads = [1, 6]
models = [
    "SignatureLSTM-2-2",
    "SignatureGRU-2-2",
    "SignatureLSTM-3-2",
    "SignatureGRU-3-2",
    "SignatureLSTM-3-3",
    "SignatureGRU-3-3",
    "SignatureLSTM-2_10-2",
    "SignatureGRU-2_10-2",
    "SignatureLSTM-3-3-3",
    "SignatureGRU-3-3-3",
    "SignatureLSTM-4-4",
    "SignatureGRU-4-4",
    "SignatureLSTM-3-3-flatten",
    "SignatureGRU-3-3-flatten",
    "GRU",
    "LSTM",
    "GRU-3",
    "LSTM-3",
    "GRU-flatten",
    "LSTM-flatten",
 ]

results = {model: {n_ahead: [] for n_ahead in n_aheads} for model in models}
results_rmse = {model: {n_ahead: [] for n_ahead in n_aheads} for model in models}
time_results = {model: {n_ahead: [] for n_ahead in n_aheads} for model in models}
for n_ahead in n_aheads:
    sequence_length = max(45, 5 * n_ahead)
    for run in range(5):
        X_train, X_test, y_train, y_test = generate_data(df, sequence_length, n_ahead)
        
        for model_id in models:

            if model_id == 'LSTM':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    LSTM(100, return_sequences=True),
                    LSTM(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'GRU':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    GRU(100, return_sequences=True),
                    GRU(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-2-2':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, return_sequences=True),
                    SignatureLSTM(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-2-2':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, return_sequences=True),
                    SignatureGRU(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-3-2':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, signature_depth=3, return_sequences=True),
                    SignatureLSTM(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-3-2':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, signature_depth=3, return_sequences=True),
                    SignatureGRU(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-3-3':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, signature_depth=3, return_sequences=True),
                    SignatureLSTM(100, signature_depth=3, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-3-3':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, signature_depth=3, return_sequences=True),
                    SignatureGRU(100, signature_depth=3, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-2_10-2':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, signature_input_size=10, return_sequences=True),
                    SignatureLSTM(100, signature_input_size=10, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-2_10-2':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, signature_input_size=10, return_sequences=True),
                    SignatureGRU(100, signature_input_size=10, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'LSTM-flatten':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    LSTM(100, return_sequences=True),
                    LSTM(100, return_sequences=True),
                    Flatten(),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'GRU-flatten':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    GRU(100, return_sequences=True),
                    GRU(100, return_sequences=True),
                    Flatten(),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'LSTM-3':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    LSTM(100, return_sequences=True),
                    LSTM(100, return_sequences=True),
                    LSTM(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'GRU-3':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    GRU(100, return_sequences=True),
                    GRU(100, return_sequences=True),
                    GRU(100, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-3-3-3':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, signature_depth=3, return_sequences=True),
                    SignatureLSTM(100, signature_depth=3, return_sequences=True),
                    SignatureLSTM(100, signature_depth=3, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-3-3-3':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, signature_depth=3, return_sequences=True),
                    SignatureGRU(100, signature_depth=3, return_sequences=True),
                    SignatureGRU(100, signature_depth=3, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-4-4':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, signature_depth=4, return_sequences=True),
                    SignatureLSTM(100, signature_depth=4, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-4-4':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, signature_depth=4, return_sequences=True),
                    SignatureGRU(100, signature_depth=4, return_sequences=False),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureLSTM-3-3-flatten':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureLSTM(100, signature_depth=3, return_sequences=True),
                    SignatureLSTM(100, signature_depth=3, return_sequences=True),
                    Flatten(),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            elif model_id == 'SignatureGRU-3-3-flatten':
                model = Sequential([
                    Input(shape=X_train.shape[1:]),
                    SignatureGRU(100, signature_depth=3, return_sequences=True),
                    SignatureGRU(100, signature_depth=3, return_sequences=True),
                    Flatten(),
                    Dense(units=n_ahead, activation='linear')
                ], name = model_id)
            else:
                raise ValueError

            optimizer = keras.optimizers.Adam(0.001)
            model.compile(optimizer=optimizer, loss='mean_squared_error', jit_compile=True)
            if run==0:
                model.summary()
                
            # Fit the model
            start_time = time.time()
            history = model.fit(X_train, y_train, batch_size=BATCH_SIZE, epochs=N_MAX_EPOCHS, validation_split=0.2, callbacks=callbacks(), shuffle=True, verbose = False)
            end_time = time.time()
            time_results[model_id][n_ahead].append(end_time - start_time)
            # Evaluate the model on the test set
            preds = model.predict(X_test, verbose=False)
            r2 = r2_score(y_true=y_test, y_pred=preds)
            print(model_id, end_time - start_time, r2)
            rmse = root_mean_squared_error(y_true=y_test, y_pred=preds)
            results[model_id][n_ahead].append(r2)
            results_rmse[model_id][n_ahead].append(rmse)
    
            del model
            del optimizer
                

print('R2 scores')
print('Means:')
df_mean_r2 = pd.DataFrame({model_id: {n_ahead: np.mean(results[model_id][n_ahead]) for n_ahead in n_aheads} for model_id in results.keys()})
df_mean_r2.to_csv('volatility_mean_r2.csv')
display(df_mean_r2)
df_mean_rmse = pd.DataFrame({model_id: {n_ahead: np.mean(results_rmse[model_id][n_ahead]) for n_ahead in n_aheads} for model_id in results_rmse.keys()})
df_mean_rmse.to_csv('volatility_mean_rmse.csv')
display(df_mean_rmse)
print('Std:')
df_std_r2 = pd.DataFrame({model_id: {n_ahead: np.std(results[model_id][n_ahead]) for n_ahead in n_aheads} for model_id in results.keys()})
df_std_r2.to_csv('volatility_std_r2.csv')
display(df_std_r2)
df_std_rmse = pd.DataFrame({model_id: {n_ahead: np.std(results_rmse[model_id][n_ahead]) for n_ahead in n_aheads} for model_id in results_rmse.keys()})
df_std_rmse.to_csv('volatility_std_rmse.csv')
display(df_std_rmse)
print('Training Times')
df_mean_time = pd.DataFrame({model_id: {n_ahead: np.mean(time_results[model_id][n_ahead]) for n_ahead in n_aheads} for model_id in time_results.keys()})
df_mean_time.to_csv('volatility_mean_time.csv')
display(df_mean_time)
df_std_time = pd.DataFrame({model_id: {n_ahead: np.std(time_results[model_id][n_ahead]) for n_ahead in n_aheads} for model_id in time_results.keys()})
df_std_time.to_csv('volatility_std_time.csv')
display(df_std_time)

Model: "SignatureLSTM-2-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm (SignatureLSTM)  │ (None, 45, 100)        │        39,195 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_1                │ (None, 100)            │        63,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 103,196 (403.11 KB)

 Trainable params: 103,196 (403.11 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-2-2 84.8414523601532 0.16556269582001348

Model: "SignatureGRU-2-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru (SignatureGRU)    │ (None, 45, 100)        │        27,195 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_1 (SignatureGRU)  │ (None, 100)            │        43,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 71,096 (277.72 KB)

 Trainable params: 71,096 (277.72 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-2-2 39.98352551460266 0.16324984276412058

Model: "SignatureLSTM-3-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_2                │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_3                │ (None, 100)            │        63,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 115,696 (451.94 KB)

 Trainable params: 115,696 (451.94 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-2 92.29347968101501 0.16816669952034857

Model: "SignatureGRU-3-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_2 (SignatureGRU)  │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_3 (SignatureGRU)  │ (None, 100)            │        43,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 83,596 (326.55 KB)

 Trainable params: 83,596 (326.55 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-2 45.525893449783325 0.16321246953603863

Model: "SignatureLSTM-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_4                │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_5                │ (None, 100)            │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 128,196 (500.77 KB)

 Trainable params: 128,196 (500.77 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3 92.46331810951233 0.15704075536650908

Model: "SignatureGRU-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_4 (SignatureGRU)  │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_5 (SignatureGRU)  │ (None, 100)            │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 96,096 (375.38 KB)

 Trainable params: 96,096 (375.38 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3 41.7785382270813 0.1341081556422966

Model: "SignatureLSTM-2_10-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_6                │ (None, 45, 100)        │        47,290 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_7                │ (None, 100)            │        72,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119,791 (467.93 KB)

 Trainable params: 119,791 (467.93 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-2_10-2 89.18003010749817 0.16755541168596366

Model: "SignatureGRU-2_10-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_6 (SignatureGRU)  │ (None, 45, 100)        │        35,290 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_7 (SignatureGRU)  │ (None, 100)            │        52,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 87,691 (342.54 KB)

 Trainable params: 87,691 (342.54 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-2_10-2 42.69538140296936 0.15345416555966573

Model: "SignatureLSTM-3-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_8                │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_9                │ (None, 45, 100)        │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_10               │ (None, 100)            │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 204,596 (799.20 KB)

 Trainable params: 204,596 (799.20 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3-3 127.51279258728027 0.16306201926776553

Model: "SignatureGRU-3-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_8 (SignatureGRU)  │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_9 (SignatureGRU)  │ (None, 45, 100)        │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_10 (SignatureGRU) │ (None, 100)            │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 152,396 (595.30 KB)

 Trainable params: 152,396 (595.30 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3-3 56.95496606826782 0.1565310603391853

Model: "SignatureLSTM-4-4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_11               │ (None, 45, 100)        │       114,195 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_12               │ (None, 100)            │       138,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 253,196 (989.05 KB)

 Trainable params: 253,196 (989.05 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-4-4 101.11166596412659 0.161152169686268

Model: "SignatureGRU-4-4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_11 (SignatureGRU) │ (None, 45, 100)        │       102,195 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_12 (SignatureGRU) │ (None, 100)            │       118,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 221,096 (863.66 KB)

 Trainable params: 221,096 (863.66 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-4-4 49.484394788742065 0.16405428440105807

Model: "SignatureLSTM-3-3-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_13               │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_14               │ (None, 45, 100)        │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_38 (Dense)                │ (None, 1)              │         4,501 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 132,596 (517.95 KB)

 Trainable params: 132,596 (517.95 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3-flatten 118.80679130554199 0.1431284647802753

Model: "SignatureGRU-3-3-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_13 (SignatureGRU) │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_14 (SignatureGRU) │ (None, 45, 100)        │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_41 (Dense)                │ (None, 1)              │         4,501 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,496 (392.56 KB)

 Trainable params: 100,496 (392.56 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3-flatten 45.32169723510742 0.15331677497865803

Model: "GRU"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru (GRU)                       │ (None, 45, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ (None, 100)            │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_44 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97,001 (378.91 KB)

 Trainable params: 97,001 (378.91 KB)

 Non-trainable params: 0 (0.00 B)

GRU 19.045171976089478 0.15469407709070015

Model: "LSTM"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 45, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 100)            │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_45 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 128,501 (501.96 KB)

 Trainable params: 128,501 (501.96 KB)

 Non-trainable params: 0 (0.00 B)

LSTM 15.004529237747192 0.16309516410724234

Model: "GRU-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_2 (GRU)                     │ (None, 45, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_3 (GRU)                     │ (None, 45, 100)        │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_4 (GRU)                     │ (None, 100)            │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_46 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 157,601 (615.63 KB)

 Trainable params: 157,601 (615.63 KB)

 Non-trainable params: 0 (0.00 B)

GRU-3 30.591100931167603 0.16309377806976466

Model: "LSTM-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_2 (LSTM)                   │ (None, 45, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 45, 100)        │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 100)            │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_47 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 208,901 (816.02 KB)

 Trainable params: 208,901 (816.02 KB)

 Non-trainable params: 0 (0.00 B)

LSTM-3 21.18918514251709 0.16169420428059655

Model: "GRU-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_5 (GRU)                     │ (None, 45, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_6 (GRU)                     │ (None, 45, 100)        │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_48 (Dense)                │ (None, 1)              │         4,501 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 101,401 (396.10 KB)

 Trainable params: 101,401 (396.10 KB)

 Non-trainable params: 0 (0.00 B)

GRU-flatten 15.467708587646484 0.12439142424651217

Model: "LSTM-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_5 (LSTM)                   │ (None, 45, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ (None, 45, 100)        │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_49 (Dense)                │ (None, 1)              │         4,501 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 132,901 (519.14 KB)

 Trainable params: 132,901 (519.14 KB)

 Non-trainable params: 0 (0.00 B)

LSTM-flatten 16.18999695777893 0.15518730202552633
SignatureLSTM-2-2 77.77110886573792 0.1624610147675627
SignatureGRU-2-2 38.700400590896606 0.1413831199816018
SignatureLSTM-3-2 88.86342430114746 0.15581244981562992
SignatureGRU-3-2 44.011714220047 0.16007924752643632
SignatureLSTM-3-3 85.51071763038635 0.14285760589437346
SignatureGRU-3-3 42.29418992996216 0.1611340228548105
SignatureLSTM-2_10-2 88.67374396324158 0.1525987086446705
SignatureGRU-2_10-2 40.910797119140625 0.15878860126532424
SignatureLSTM-3-3-3 123.02487969398499 0.16467864944541066
SignatureGRU-3-3-3 54.28394031524658 0.15762539611646664
SignatureLSTM-4-4 95.76565027236938 0.16317091092932
SignatureGRU-4-4 52.359630823135376 0.16054186620502453
SignatureLSTM-3-3-flatten 117.04255771636963 0.157791985641917
SignatureGRU-3-3-flatten 41.33333492279053 0.13913859346727286
GRU 15.059874057769775 0.16224577499215798
LSTM 14.351263761520386 0.16059593090682156
GRU-3 21.350672721862793 0.15412760357466038
LSTM-3 23.976394653320312 0.16156498250847906
GRU-flatten 16.67018151283264 0.153450028074816
LSTM-flatten 14.069119453430176 0.1496804974724899
SignatureLSTM-2-2 79.85628938674927 0.14004014210074667
SignatureGRU-2-2 37.861257553100586 0.15067713741421584
SignatureLSTM-3-2 84.95717120170593 0.16655123951113648
SignatureGRU-3-2 41.58138632774353 0.1438537740147059
SignatureLSTM-3-3 84.8307294845581 0.1418825090765159
SignatureGRU-3-3 39.90051627159119 0.14676649235227746
SignatureLSTM-2_10-2 86.07056140899658 0.1614191253248054
SignatureGRU-2_10-2 42.67125868797302 0.1429136774663804
SignatureLSTM-3-3-3 118.81345200538635 0.1586904787430673
SignatureGRU-3-3-3 52.707958459854126 0.15661521580404747
SignatureLSTM-4-4 94.04130983352661 0.15716559385572415
SignatureGRU-4-4 48.38226366043091 0.15179480628724362
SignatureLSTM-3-3-flatten 111.30424213409424 0.1573674638749546
SignatureGRU-3-3-flatten 42.684913635253906 0.14584786428808505
GRU 15.947340250015259 0.16444779713298596
LSTM 13.80136251449585 0.16386781468038059
GRU-3 24.71493673324585 0.1660516876827398
LSTM-3 20.626023292541504 0.1587349566203562
GRU-flatten 17.428455114364624 0.13144106655972698
LSTM-flatten 13.894292116165161 0.1585695867721948
SignatureLSTM-2-2 79.6084942817688 0.16475659772398532
SignatureGRU-2-2 39.591867446899414 0.1541537498111878
SignatureLSTM-3-2 81.88712763786316 0.16483723905276115
SignatureGRU-3-2 43.30109214782715 0.146427743903205
SignatureLSTM-3-3 84.77442288398743 0.16448958586902462
SignatureGRU-3-3 43.18574810028076 0.16374673752708513
SignatureLSTM-2_10-2 84.53314328193665 0.1672038417524604
SignatureGRU-2_10-2 42.47140121459961 0.15298262443324773
SignatureLSTM-3-3-3 123.20782113075256 0.1644779432053053
SignatureGRU-3-3-3 56.03591752052307 0.135803384238529
SignatureLSTM-4-4 89.50430393218994 0.16409734562065104
SignatureGRU-4-4 45.52678179740906 0.16106752190506146
SignatureLSTM-3-3-flatten 117.71958184242249 0.13941538868796466
SignatureGRU-3-3-flatten 41.82310652732849 0.1383812634543654
GRU 17.874300241470337 0.1595709243386504
LSTM 17.45600938796997 0.16312016930415318
GRU-3 22.781982898712158 0.1469359770462373
LSTM-3 19.897642374038696 0.13359158730007148
GRU-flatten 15.221293687820435 0.15926354022224276
LSTM-flatten 13.928734540939331 0.1592023534344038
SignatureLSTM-2-2 81.03826117515564 0.16567691684820673
SignatureGRU-2-2 38.88052153587341 0.1560346713972055
SignatureLSTM-3-2 86.70184135437012 0.16549929736940006
SignatureGRU-3-2 41.319817543029785 0.13785548769845724
SignatureLSTM-3-3 86.55555176734924 0.1658599229693134
SignatureGRU-3-3 43.82377624511719 0.15398750216237223
SignatureLSTM-2_10-2 77.12752604484558 0.16659743937952542
SignatureGRU-2_10-2 43.17859244346619 0.15702169641391994
SignatureLSTM-3-3-3 117.7211434841156 0.16773234307667473
SignatureGRU-3-3-3 56.79908537864685 0.14439221039591588
SignatureLSTM-4-4 85.34987354278564 0.1671242797037057
SignatureGRU-4-4 47.96269917488098 0.1572885808085389
SignatureLSTM-3-3-flatten 116.53617453575134 0.15995916234079333
SignatureGRU-3-3-flatten 42.67256808280945 0.14549316425632175
GRU 17.22600507736206 0.16115317235640447
LSTM 13.791850566864014 0.15928129304815608
GRU-3 22.595569133758545 0.15172863738659859
LSTM-3 19.612820386886597 0.15070044125843884
GRU-flatten 18.25090527534485 0.1458491501539575
LSTM-flatten 14.020012617111206 0.15274366107385207

Model: "SignatureLSTM-2-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_75               │ (None, 45, 100)        │        39,195 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_76               │ (None, 100)            │        63,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_250 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 103,701 (405.08 KB)

 Trainable params: 103,701 (405.08 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-2-2 91.88126397132874 0.1308441446417133

Model: "SignatureGRU-2-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_75 (SignatureGRU) │ (None, 45, 100)        │        27,195 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_76 (SignatureGRU) │ (None, 100)            │        43,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_253 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 71,601 (279.69 KB)

 Trainable params: 71,601 (279.69 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-2-2 40.08151292800903 0.09958662961201241

Model: "SignatureLSTM-3-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_77               │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_78               │ (None, 100)            │        63,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_256 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 116,201 (453.91 KB)

 Trainable params: 116,201 (453.91 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-2 98.91338539123535 0.139283527035888

Model: "SignatureGRU-3-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_77 (SignatureGRU) │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_78 (SignatureGRU) │ (None, 100)            │        43,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_259 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 84,101 (328.52 KB)

 Trainable params: 84,101 (328.52 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-2 42.89638113975525 0.1202626999092623

Model: "SignatureLSTM-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_79               │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_80               │ (None, 100)            │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_262 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 128,701 (502.74 KB)

 Trainable params: 128,701 (502.74 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3 102.20572829246521 0.13637979294134137

Model: "SignatureGRU-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_79 (SignatureGRU) │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_80 (SignatureGRU) │ (None, 100)            │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_265 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 96,601 (377.35 KB)

 Trainable params: 96,601 (377.35 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3 41.35762810707092 0.11875338224959792

Model: "SignatureLSTM-2_10-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_81               │ (None, 45, 100)        │        47,290 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_82               │ (None, 100)            │        72,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_268 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 120,296 (469.91 KB)

 Trainable params: 120,296 (469.91 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-2_10-2 96.97421455383301 0.1356658905788222

Model: "SignatureGRU-2_10-2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_81 (SignatureGRU) │ (None, 45, 100)        │        35,290 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_82 (SignatureGRU) │ (None, 100)            │        52,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_271 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 88,196 (344.52 KB)

 Trainable params: 88,196 (344.52 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-2_10-2 39.934306144714355 0.11741677476245203

Model: "SignatureLSTM-3-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_83               │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_84               │ (None, 45, 100)        │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_85               │ (None, 100)            │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_274 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 205,101 (801.18 KB)

 Trainable params: 205,101 (801.18 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3-3 134.5227620601654 0.12554673736474695

Model: "SignatureGRU-3-3-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_83 (SignatureGRU) │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_84 (SignatureGRU) │ (None, 45, 100)        │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_85 (SignatureGRU) │ (None, 100)            │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_278 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 152,901 (597.27 KB)

 Trainable params: 152,901 (597.27 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3-3 53.41231846809387 0.10785372750101113

Model: "SignatureLSTM-4-4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_86               │ (None, 45, 100)        │       114,195 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_87               │ (None, 100)            │       138,900 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_282 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 253,701 (991.02 KB)

 Trainable params: 253,701 (991.02 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-4-4 107.11424160003662 0.13418397049366929

Model: "SignatureGRU-4-4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_86 (SignatureGRU) │ (None, 45, 100)        │       102,195 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_87 (SignatureGRU) │ (None, 100)            │       118,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_285 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 221,601 (865.63 KB)

 Trainable params: 221,601 (865.63 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-4-4 46.94812774658203 0.1240089775461307

Model: "SignatureLSTM-3-3-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_lstm_88               │ (None, 45, 100)        │        51,695 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_lstm_89               │ (None, 45, 100)        │        76,400 │
│ (SignatureLSTM)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_20 (Flatten)            │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_288 (Dense)               │ (None, 6)              │        27,006 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 155,101 (605.86 KB)

 Trainable params: 155,101 (605.86 KB)

 Non-trainable params: 0 (0.00 B)

SignatureLSTM-3-3-flatten 106.23311138153076 0.11583560015539773

Model: "SignatureGRU-3-3-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ signature_gru_88 (SignatureGRU) │ (None, 45, 100)        │        39,695 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ signature_gru_89 (SignatureGRU) │ (None, 45, 100)        │        56,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_21 (Flatten)            │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_291 (Dense)               │ (None, 6)              │        27,006 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 123,001 (480.47 KB)

 Trainable params: 123,001 (480.47 KB)

 Non-trainable params: 0 (0.00 B)

SignatureGRU-3-3-flatten 42.09076189994812 0.10971452357499713

Model: "GRU"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_35 (GRU)                    │ (None, 45, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_36 (GRU)                    │ (None, 100)            │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_294 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97,506 (380.88 KB)

 Trainable params: 97,506 (380.88 KB)

 Non-trainable params: 0 (0.00 B)

GRU 16.27862024307251 0.1190831036756725

Model: "LSTM"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_35 (LSTM)                  │ (None, 45, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_36 (LSTM)                  │ (None, 100)            │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_295 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129,006 (503.93 KB)

 Trainable params: 129,006 (503.93 KB)

 Non-trainable params: 0 (0.00 B)

LSTM 14.481226921081543 0.11497410749575326

Model: "GRU-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_37 (GRU)                    │ (None, 45, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_38 (GRU)                    │ (None, 45, 100)        │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_39 (GRU)                    │ (None, 100)            │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_296 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 158,106 (617.60 KB)

 Trainable params: 158,106 (617.60 KB)

 Non-trainable params: 0 (0.00 B)

GRU-3 22.224430084228516 0.0888016060422207

Model: "LSTM-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_37 (LSTM)                  │ (None, 45, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_38 (LSTM)                  │ (None, 45, 100)        │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_39 (LSTM)                  │ (None, 100)            │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_297 (Dense)               │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 209,406 (817.99 KB)

 Trainable params: 209,406 (817.99 KB)

 Non-trainable params: 0 (0.00 B)

LSTM-3 20.233553171157837 0.13106934744635926

Model: "GRU-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_40 (GRU)                    │ (None, 45, 100)        │        36,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_41 (GRU)                    │ (None, 45, 100)        │        60,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_22 (Flatten)            │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_298 (Dense)               │ (None, 6)              │        27,006 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 123,906 (484.01 KB)

 Trainable params: 123,906 (484.01 KB)

 Non-trainable params: 0 (0.00 B)

GRU-flatten 15.746596813201904 0.11914064139947121

Model: "LSTM-flatten"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_40 (LSTM)                  │ (None, 45, 100)        │        48,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_41 (LSTM)                  │ (None, 45, 100)        │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_23 (Flatten)            │ (None, 4500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_299 (Dense)               │ (None, 6)              │        27,006 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 155,406 (607.05 KB)

 Trainable params: 155,406 (607.05 KB)

 Non-trainable params: 0 (0.00 B)

LSTM-flatten 14.58005142211914 0.12825556287646236
SignatureLSTM-2-2 89.24496507644653 0.13487170130865753
SignatureGRU-2-2 38.746042251586914 0.11824454664792396
SignatureLSTM-3-2 93.63941788673401 0.1368356546124251
SignatureGRU-3-2 43.96084547042847 0.11885853663701813
SignatureLSTM-3-3 88.59031367301941 0.1371621781208514
SignatureGRU-3-3 42.35911822319031 0.11263521082374217
SignatureLSTM-2_10-2 91.07406854629517 0.129642424317282
SignatureGRU-2_10-2 39.096948862075806 0.1136315609146845
SignatureLSTM-3-3-3 131.9622302055359 0.13564509710947184
SignatureGRU-3-3-3 65.0331609249115 0.11536571863054516
SignatureLSTM-4-4 100.6708197593689 0.13120112924245494
SignatureGRU-4-4 45.955573081970215 0.1198003578687571
SignatureLSTM-3-3-flatten 92.23857402801514 0.12130870371629571
SignatureGRU-3-3-flatten 40.432807207107544 0.10781117249104015
GRU 15.438321590423584 0.12441018194507332
LSTM 14.263898134231567 0.12176578505765345
GRU-3 22.01573371887207 0.12601209104188835
LSTM-3 22.62709903717041 0.12059445443454592
GRU-flatten 21.892131328582764 0.11405654338504197
LSTM-flatten 14.29869794845581 0.11715406851283461
SignatureLSTM-2-2 85.3243761062622 0.13378646968281607
SignatureGRU-2-2 38.882752418518066 0.11731894938250154
SignatureLSTM-3-2 91.07899308204651 0.12650310946336477
SignatureGRU-3-2 41.815330028533936 0.12052479928471611
SignatureLSTM-3-3 91.69036149978638 0.12150243080269103
SignatureGRU-3-3 43.469807386398315 0.11597775639541708
SignatureLSTM-2_10-2 94.27827596664429 0.12265939215118067
SignatureGRU-2_10-2 38.3794949054718 0.10818150434951031
SignatureLSTM-3-3-3 127.31674766540527 0.13920581018873765
SignatureGRU-3-3-3 53.82967805862427 0.11791296953537082
SignatureLSTM-4-4 96.14455199241638 0.13638477988687456
SignatureGRU-4-4 44.33654308319092 0.1214614320554993
SignatureLSTM-3-3-flatten 95.91545844078064 0.1285560907189695
SignatureGRU-3-3-flatten 40.57085394859314 0.10926110816007566
GRU 15.673930406570435 0.1322689459449711
LSTM 14.278981924057007 0.13376100376464414
GRU-3 24.135035514831543 0.12303922512702385
LSTM-3 19.971862077713013 0.12614971107899153
GRU-flatten 15.227007627487183 0.11701562656351432
LSTM-flatten 14.105846405029297 0.12176417421791992
SignatureLSTM-2-2 86.93149924278259 0.13088369899500502
SignatureGRU-2-2 38.03692412376404 0.11088833720976292
SignatureLSTM-3-2 93.71368312835693 0.1366240296390444
SignatureGRU-3-2 42.741852045059204 0.11780905006023994
SignatureLSTM-3-3 86.6030650138855 0.13663068743902668
SignatureGRU-3-3 43.13856077194214 0.1091020249233285
SignatureLSTM-2_10-2 87.23280048370361 0.13595483725573757
SignatureGRU-2_10-2 40.33325695991516 0.10671666550029017
SignatureLSTM-3-3-3 128.04999899864197 0.13579482284717906
SignatureGRU-3-3-3 55.30531191825867 0.10609550385418519
SignatureLSTM-4-4 93.17064666748047 0.126045036608487
SignatureGRU-4-4 51.130481243133545 0.11924929375960036
SignatureLSTM-3-3-flatten 89.98392653465271 0.11339782704212181
SignatureGRU-3-3-flatten 39.92821764945984 0.11234017302066619
GRU 15.45876932144165 0.13654615024875058
LSTM 14.167911291122437 0.13452845476244815
GRU-3 21.940750122070312 0.1329233548214487
LSTM-3 19.86884331703186 0.12780490151369792
GRU-flatten 20.12526798248291 0.1127991049627592
LSTM-flatten 16.840464115142822 0.12007024275041926
SignatureLSTM-2-2 85.05823302268982 0.1259992177626123
SignatureGRU-2-2 42.55138373374939 0.12136766167995315
SignatureLSTM-3-2 88.32289433479309 0.11679712385914343
SignatureGRU-3-2 42.52025127410889 0.09023793592921987
SignatureLSTM-3-3 89.86778020858765 0.12440059958721322
SignatureGRU-3-3 40.22188115119934 0.11918094847571474
SignatureLSTM-2_10-2 91.12492322921753 0.12507114067347871
SignatureGRU-2_10-2 39.150891065597534 0.10961326569533775
SignatureLSTM-3-3-3 128.52975130081177 0.12563065752812266
SignatureGRU-3-3-3 60.07934331893921 0.12426786020161006
SignatureLSTM-4-4 97.71249413490295 0.12382613599496607
SignatureGRU-4-4 45.42292070388794 0.126361394938847
SignatureLSTM-3-3-flatten 95.54550123214722 0.10852494785553414
SignatureGRU-3-3-flatten 38.821826219558716 0.12040119548031931
GRU 16.206348180770874 0.11930727490058952
LSTM 14.14198899269104 0.12334969073137508
GRU-3 25.7041757106781 0.1242609054395693
LSTM-3 20.188132524490356 0.11821333222164544
GRU-flatten 16.79572629928589 0.11514966134340421
LSTM-flatten 14.280827045440674 0.1299777527983561
R2 scores
Means:

,SignatureLSTM-2-2,SignatureGRU-2-2,SignatureLSTM-3-2,SignatureGRU-3-2,SignatureLSTM-3-3,SignatureGRU-3-3,SignatureLSTM-2_10-2,SignatureGRU-2_10-2,SignatureLSTM-3-3-3,SignatureGRU-3-3-3,SignatureLSTM-4-4,SignatureGRU-4-4,SignatureLSTM-3-3-flatten,SignatureGRU-3-3-flatten,GRU,LSTM,GRU-3,LSTM-3,GRU-flatten,LSTM-flatten
1,0.159699,0.153100,0.164173,0.150286,0.154426,0.151949,0.163075,0.153032,0.163728,0.150193,0.162542,0.158949,0.151532,0.144436,0.160422,0.161992,0.156388,0.153257,0.142879,0.155077
6,0.131277,0.113481,0.131209,0.113539,0.131215,0.115130,0.129799,0.111112,0.132365,0.114299,0.130328,0.122176,0.117525,0.111906,0.126323,0.125676,0.119007,0.124766,0.115632,0.123444

,SignatureLSTM-2-2,SignatureGRU-2-2,SignatureLSTM-3-2,SignatureGRU-3-2,SignatureLSTM-3-3,SignatureGRU-3-3,SignatureLSTM-2_10-2,SignatureGRU-2_10-2,SignatureLSTM-3-3-3,SignatureGRU-3-3-3,SignatureLSTM-4-4,SignatureGRU-4-4,SignatureLSTM-3-3-flatten,SignatureGRU-3-3-flatten,GRU,LSTM,GRU-3,LSTM-3,GRU-flatten,LSTM-flatten
1,0.026123,0.026225,0.026054,0.026269,0.026205,0.026243,0.026071,0.026227,0.026061,0.026270,0.026079,0.026135,0.026250,0.026359,0.026112,0.026088,0.026175,0.026223,0.026383,0.026195
6,0.026565,0.026836,0.026566,0.026832,0.026565,0.026810,0.026588,0.026870,0.026549,0.026823,0.026579,0.026704,0.026775,0.026859,0.026641,0.026650,0.026750,0.026665,0.026804,0.026685

Std:

,SignatureLSTM-2-2,SignatureGRU-2-2,SignatureLSTM-3-2,SignatureGRU-3-2,SignatureLSTM-3-3,SignatureGRU-3-3,SignatureLSTM-2_10-2,SignatureGRU-2_10-2,SignatureLSTM-3-3-3,SignatureGRU-3-3-3,SignatureLSTM-4-4,SignatureGRU-4-4,SignatureLSTM-3-3-flatten,SignatureGRU-3-3-flatten,GRU,LSTM,GRU-3,LSTM-3,GRU-flatten,LSTM-flatten
1,0.009897,0.007154,0.004329,0.009734,0.010296,0.010704,0.005693,0.005507,0.002944,0.008688,0.003306,0.004172,0.008505,0.005417,0.003274,0.001750,0.007135,0.010616,0.013127,0.003572
6,0.003079,0.007738,0.008438,0.011692,0.006814,0.003816,0.005398,0.003905,0.005677,0.006670,0.004753,0.002668,0.006883,0.004493,0.007002,0.007469,0.015485,0.004716,0.002235,0.004891

,SignatureLSTM-2-2,SignatureGRU-2-2,SignatureLSTM-3-2,SignatureGRU-3-2,SignatureLSTM-3-3,SignatureGRU-3-3,SignatureLSTM-2_10-2,SignatureGRU-2_10-2,SignatureLSTM-3-3-3,SignatureGRU-3-3-3,SignatureLSTM-4-4,SignatureGRU-4-4,SignatureLSTM-3-3-flatten,SignatureGRU-3-3-flatten,GRU,LSTM,GRU-3,LSTM-3,GRU-flatten,LSTM-flatten
1,0.000153,0.000111,0.000067,0.000151,0.000159,0.000165,0.000089,0.000085,0.000046,0.000134,0.000051,0.000065,0.000131,0.000083,0.000051,0.000027,0.000111,0.000164,0.000202,0.000055
6,0.000047,0.000117,0.000128,0.000173,0.000103,0.000058,0.000082,0.000059,0.000087,0.000101,0.000072,0.000041,0.000105,0.000068,0.000107,0.000113,0.000232,0.000072,0.000034,0.000074

Training Times

,SignatureLSTM-2-2,SignatureGRU-2-2,SignatureLSTM-3-2,SignatureGRU-3-2,SignatureLSTM-3-3,SignatureGRU-3-3,SignatureLSTM-2_10-2,SignatureGRU-2_10-2,SignatureLSTM-3-3-3,SignatureGRU-3-3-3,SignatureLSTM-4-4,SignatureGRU-4-4,SignatureLSTM-3-3-flatten,SignatureGRU-3-3-flatten,GRU,LSTM,GRU-3,LSTM-3,GRU-flatten,LSTM-flatten
1,80.623121,39.003515,86.940609,43.147981,86.826948,42.196554,85.117001,42.385486,122.056018,55.356374,93.154561,48.743154,116.281870,42.767124,17.030538,14.881003,24.406852,21.060413,16.607709,14.420431
6,87.688067,39.659723,93.133675,42.786932,91.791450,42.109399,92.136857,39.378980,130.076298,57.531963,98.962551,46.758729,95.983314,40.368893,15.811198,14.266801,23.204025,20.577898,17.957346,14.821177

,SignatureLSTM-2-2,SignatureGRU-2-2,SignatureLSTM-3-2,SignatureGRU-3-2,SignatureLSTM-3-3,SignatureGRU-3-3,SignatureLSTM-2_10-2,SignatureGRU-2_10-2,SignatureLSTM-3-3-3,SignatureGRU-3-3-3,SignatureLSTM-4-4,SignatureGRU-4-4,SignatureLSTM-3-3-flatten,SignatureGRU-3-3-flatten,GRU,LSTM,GRU-3,LSTM-3,GRU-flatten,LSTM-flatten
1,2.354491,0.737338,3.517930,1.563352,2.890416,1.347770,4.341440,0.773150,3.502773,1.628675,5.388082,2.223184,2.602397,1.377568,1.404687,1.362235,3.274173,1.559217,1.148858,0.886984
6,2.572248,1.588180,3.503215,0.693861,5.465062,1.191648,3.292081,0.685502,2.736443,4.436068,4.741691,2.342841,5.572618,1.058047,0.362412,0.119576,1.488962,1.033417,2.602842,1.021011